-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.26 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for thepinrealestate_social_login
DROP DATABASE IF EXISTS `thepinrealestate_social_login`;
CREATE DATABASE IF NOT EXISTS `thepinrealestate_social_login` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `thepinrealestate_social_login`;

-- Dumping structure for table thepinrealestate_social_login.communes
DROP TABLE IF EXISTS `communes`;
CREATE TABLE IF NOT EXISTS `communes` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `district_id` int(11) DEFAULT NULL,
  `name_en` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name_kh` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=944 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table thepinrealestate_social_login.communes: 943 rows
/*!40000 ALTER TABLE `communes` DISABLE KEYS */;
INSERT INTO `communes` (`id`, `district_id`, `name_en`, `name_kh`, `slug`, `created_at`, `updated_at`) VALUES
	(1, 1, 'Svay Pak', '', 'svay-pak', NULL, NULL),
	(2, 1, 'Russey Keo', '', 'russey-keo', NULL, NULL),
	(3, 1, 'Toul Sangke', '', 'toul-sangke', NULL, NULL),
	(4, 1, 'Kilometr Lek 6', '', 'kilometr-lek-6', NULL, NULL),
	(5, 1, 'Chrang Chamreh 1', '', 'chrang-chamreh-1', NULL, NULL),
	(6, 1, 'Chrang Chamreh 2', '', 'chrang-chamreh-2', NULL, NULL),
	(7, 2, 'Krang Thnong', '', 'krang-thnong', NULL, NULL),
	(8, 2, 'Khmuonh', '', 'khmuonh', NULL, NULL),
	(9, 2, 'Phnom Penh Thmei', '', 'phnom-penh-thmei', NULL, NULL),
	(10, 2, 'Tuek Thla', '', 'tuek-thla', NULL, NULL),
	(11, 2, 'Obek Kaom', '', 'obek-kaom', NULL, NULL),
	(12, 3, 'Ovlaok', '', 'ovlaok', NULL, NULL),
	(13, 3, 'Kamboul', '', 'kamboul', NULL, NULL),
	(14, 3, 'Kantaok', '', 'kantaok', NULL, NULL),
	(15, 3, 'Boeng Thum', '', 'boeng-thum', NULL, NULL),
	(16, 3, 'Phleung Chheh Roteh', '', 'phleung-chheh-roteh', NULL, NULL),
	(17, 3, 'Chaom Chau', '', 'chaom-chau', NULL, NULL),
	(18, 3, 'Trapeang Krasang', '', 'trapeang-krasang', NULL, NULL),
	(19, 3, 'Kakab', '', 'kakab', NULL, NULL),
	(20, 3, 'Samraong Kraom', '', 'samraong-kraom', NULL, NULL),
	(21, 3, 'Snaor', '', 'snaor', NULL, NULL),
	(22, 4, 'Bak Kheng', '', 'bak-kheng', NULL, NULL),
	(23, 4, 'Praek Leab', '', 'praek-leab', NULL, NULL),
	(24, 4, 'Praek Ta Sek', '', 'praek-ta-sek', NULL, NULL),
	(25, 4, 'Chrouy Changvar', '', 'chrouy-changvar', NULL, NULL),
	(26, 4, 'Kaoh Dach', '', 'kaoh-dach', NULL, NULL),
	(27, 5, 'Ponsang', '', 'ponsang', NULL, NULL),
	(28, 5, 'Kouk Roka', '', 'kouk-roka', NULL, NULL),
	(29, 5, 'Ponhea Pon', '', 'ponhea-pon', NULL, NULL),
	(30, 5, 'Samraong', '', 'samraong', NULL, NULL),
	(31, 5, 'Praek Phnov', '', 'praek-phnov', NULL, NULL),
	(32, 6, 'Veal Sbov', '', 'veal-sbov', NULL, NULL),
	(33, 6, 'Praek Aeng', '', 'praek-aeng', NULL, NULL),
	(34, 6, 'Chbar Ampov 1', '', 'chbar-ampov-1', NULL, NULL),
	(35, 6, 'Chbar Ampov 2', '', 'chbar-ampov-2', NULL, NULL),
	(36, 6, 'Nirouth', '', 'nirouth', NULL, NULL),
	(37, 6, 'Praek Pra', '', 'praek-pra', NULL, NULL),
	(38, 6, 'Praek Thmei', '', 'praek-thmei', NULL, NULL),
	(39, 6, 'Kbal Kaoh', '', 'kbal-kaoh', NULL, NULL),
	(40, 7, 'Psar Thmei1', '', 'psar-thmei1', NULL, NULL),
	(41, 7, 'Psar Thmei2', '', 'psar-thmei2', NULL, NULL),
	(42, 7, 'Psar Thmei3', '', 'psar-thmei3', NULL, NULL),
	(43, 7, 'Boeung Reang', '', 'boeung-reang', NULL, NULL),
	(44, 7, 'Psar Kandal1', '', 'psar-kandal1', NULL, NULL),
	(45, 7, 'Psar Kandal2', '', 'psar-kandal2', NULL, NULL),
	(46, 7, 'Chaktomukh', '', 'chaktomukh', NULL, NULL),
	(47, 7, 'Chey Chumneah', '', 'chey-chumneah', NULL, NULL),
	(48, 7, 'Psar Chas', '', 'psar-chas', NULL, NULL),
	(49, 7, 'Srah Chork', '', 'srah-chork', NULL, NULL),
	(50, 7, 'Vat Phnum', '', 'vat-phnum', NULL, NULL),
	(51, 8, 'O Reussei 1', '', 'o-reussei-1', NULL, NULL),
	(52, 8, 'O Reussei 2', '', 'o-reussei-2', NULL, NULL),
	(53, 8, 'O Reussei 3', '', 'o-reussei-3', NULL, NULL),
	(54, 8, 'O Reussei 4', '', 'o-reussei-4', NULL, NULL),
	(55, 8, 'Monorom', '', 'monorom', NULL, NULL),
	(56, 8, 'Mittapheap', '', 'mittapheap', NULL, NULL),
	(57, 8, 'Vealvong', '', 'vealvong', NULL, NULL),
	(58, 8, 'Beung Prolit', '', 'beung-prolit', NULL, NULL),
	(59, 9, 'Psar Depot1', '', 'psar-depot1', NULL, NULL),
	(60, 9, 'Psar Depot2', '', 'psar-depot2', NULL, NULL),
	(61, 9, 'Psar Depot3', '', 'psar-depot3', NULL, NULL),
	(62, 9, 'Teuk Laork1', '', 'teuk-laork1', NULL, NULL),
	(63, 9, 'Teuk Laork2', '', 'teuk-laork2', NULL, NULL),
	(64, 9, 'Teuk Laork3', '', 'teuk-laork3', NULL, NULL),
	(65, 9, 'Beung Kok1', '', 'beung-kok1', NULL, NULL),
	(66, 9, 'Beung Kok2', '', 'beung-kok2', NULL, NULL),
	(67, 9, 'Psar Deumkor', '', 'psar-deumkor', NULL, NULL),
	(68, 9, 'Beung Salang', '', 'beung-salang', NULL, NULL),
	(69, 10, 'Dangkor', '', 'dangkor', NULL, NULL),
	(70, 10, 'Prey Sa', '', 'prey-sa', NULL, NULL),
	(71, 10, 'Cheung Aek', '', 'cheung-aek', NULL, NULL),
	(72, 10, 'Spean Thma', '', 'spean-thma', NULL, NULL),
	(73, 10, 'Prey Vaeng', '', 'prey-vaeng', NULL, NULL),
	(74, 10, 'Pong Tuek', '', 'pong-tuek', NULL, NULL),
	(75, 10, 'Prateah Lang', '', 'prateah-lang', NULL, NULL),
	(76, 10, 'Sak Sampov', '', 'sak-sampov', NULL, NULL),
	(77, 10, 'Krang Pongro', '', 'krang-pongro', NULL, NULL),
	(78, 10, 'Kong Noy', '', 'kong-noy', NULL, NULL),
	(79, 10, 'Tien', '', 'tien', NULL, NULL),
	(80, 10, 'Praek Kampues', '', 'praek-kampues', NULL, NULL),
	(81, 11, 'Stung Meanchey', '', 'stung-meanchey', NULL, NULL),
	(82, 11, 'Boeng Tompun', '', 'boeng-tompun', NULL, NULL),
	(83, 11, 'Chak Angrae Leu', '', 'chak-angrae-leu', NULL, NULL),
	(84, 11, 'Chak Angrae Kroam', '', 'chak-angrae-kroam', NULL, NULL),
	(85, 12, 'Tonle Bassac', '', 'tonle-bassac', NULL, NULL),
	(86, 12, 'Beung Kengkang1', '', 'beung-kengkang1', NULL, NULL),
	(87, 12, 'Beung Kengkang2', '', 'beung-kengkang2', NULL, NULL),
	(88, 12, 'Beung Kengkang3', '', 'beung-kengkang3', NULL, NULL),
	(89, 12, 'Olympic', '', 'olympic', NULL, NULL),
	(90, 12, 'Toul Svayprey1', '', 'toul-svayprey1', NULL, NULL),
	(91, 12, 'Toul Svayprey2', '', 'toul-svayprey2', NULL, NULL),
	(92, 12, 'Tomnub Teuk', '', 'tomnub-teuk', NULL, NULL),
	(93, 12, 'Toul Tompung1', '', 'toul-tompung1', NULL, NULL),
	(94, 12, 'Toul Tompung2', '', 'toul-tompung2', NULL, NULL),
	(95, 12, 'Beung Trabaek', '', 'beung-trabaek', NULL, NULL),
	(96, 12, 'Psar Deumtkov', '', 'psar-deumtkov', NULL, NULL),
	(97, 13, 'Sangkat 1', '', 'sangkat-1', NULL, NULL),
	(98, 13, 'Sangkat 2', '', 'sangkat-2', NULL, NULL),
	(99, 13, 'Sangkat 3', '', 'sangkat-3', NULL, NULL),
	(100, 13, 'Sangkat 4', '', 'sangkat-4', NULL, NULL),
	(101, 13, 'Koh Rong', '', 'koh-rong', NULL, NULL),
	(102, 14, 'Andong Thmar', '', 'andong-thmar', NULL, NULL),
	(103, 14, 'Beung Taprum', '', 'beung-taprum', NULL, NULL),
	(104, 14, 'Bet Trang', '', 'bet-trang', NULL, NULL),
	(105, 14, 'Cheung Koar', '', 'cheung-koar', NULL, NULL),
	(106, 14, 'Ou Chrov', '', 'ou-chrov', NULL, NULL),
	(107, 14, 'Ou Oknha Heng', '', 'ou-oknha-heng', NULL, NULL),
	(108, 14, 'Prey Nob', '', 'prey-nob', NULL, NULL),
	(109, 14, 'Ream', '', 'ream', NULL, NULL),
	(110, 14, 'Sammaki', '', 'sammaki', NULL, NULL),
	(111, 14, 'Somrong', '', 'somrong', NULL, NULL),
	(112, 14, 'Teuk Laork', '', 'teuk-laork', NULL, NULL),
	(113, 14, 'Teuk Tla', '', 'teuk-tla', NULL, NULL),
	(114, 14, 'Toul Toteung', '', 'toul-toteung', NULL, NULL),
	(115, 14, 'Veal Rinh', '', 'veal-rinh', NULL, NULL),
	(116, 15, 'Kompenh', '', 'kompenh', NULL, NULL),
	(117, 15, 'Ou Treh', '', 'ou-treh', NULL, NULL),
	(118, 15, 'Tomnob Rolork', '', 'tomnob-rolork', NULL, NULL),
	(119, 15, 'Keo Phos', '', 'keo-phos', NULL, NULL),
	(120, 16, 'Chomkar Loung', '', 'chomkar-loung', NULL, NULL),
	(121, 16, 'Kampong Seila', '', 'kampong-seila', NULL, NULL),
	(122, 16, 'Ou Bak Roteh', '', 'ou-bak-roteh', NULL, NULL),
	(123, 16, 'Steung Chhay', '', 'steung-chhay', NULL, NULL),
	(124, 17, 'Boeng Kok', '', 'boeng-kok', NULL, NULL),
	(125, 17, 'Kampong Cham', '', 'kampong-cham', NULL, NULL),
	(126, 17, 'Sambuor Meas', '', 'sambuor-meas', NULL, NULL),
	(127, 17, 'Veal Vong', '', 'veal-vong', NULL, NULL),
	(128, 18, 'Ampil', '', 'ampil', NULL, NULL),
	(129, 18, 'Hann Chey', '', 'hann-chey', NULL, NULL),
	(130, 18, 'Kien Chrey', '', 'kien-chrey', NULL, NULL),
	(131, 18, 'Kokor', '', 'kokor', NULL, NULL),
	(132, 18, 'Kaoh Mitt', '', 'kaoh-mitt', NULL, NULL),
	(133, 18, 'Kaoh Roka', '', 'kaoh-roka', NULL, NULL),
	(134, 18, 'Kaoh Samraong', '', 'kaoh-samraong', NULL, NULL),
	(135, 18, 'Kaoh Tontuem', '', 'kaoh-tontuem', NULL, NULL),
	(136, 18, 'Krala', '', 'krala', NULL, NULL),
	(137, 18, 'Ou Svay', '', 'ou-svay', NULL, NULL),
	(138, 18, 'Ro any', '', 'ro-any', NULL, NULL),
	(139, 18, 'Rumchek', '', 'rumchek', NULL, NULL),
	(140, 18, 'Srak', '', 'srak', NULL, NULL),
	(141, 18, 'Trean', '', 'trean', NULL, NULL),
	(142, 18, 'Vihear Thum', '', 'vihear-thum', NULL, NULL),
	(143, 19, 'Angkor Ban', '', 'angkor-ban', NULL, NULL),
	(144, 19, 'Kong Taneung', '', 'kong-taneung', NULL, NULL),
	(145, 19, 'Khchau', '', 'khchau', NULL, NULL),
	(146, 19, 'Peam Chikong', '', 'peam-chikong', NULL, NULL),
	(147, 19, 'Prek Koy', '', 'prek-koy', NULL, NULL),
	(148, 19, 'Prek Krabau', '', 'prek-krabau', NULL, NULL),
	(149, 19, 'Reay Pay', '', 'reay-pay', NULL, NULL),
	(150, 19, 'Roka-a', '', 'roka-a', NULL, NULL),
	(151, 19, 'Roka-koy', '', 'roka-koy', NULL, NULL),
	(152, 19, 'Sdau', '', 'sdau', NULL, NULL),
	(153, 19, 'Sor Korng', '', 'sor-korng', NULL, NULL),
	(154, 20, 'Kampong Reab', '', 'kampong-reab', NULL, NULL),
	(155, 20, 'Koh Sotin', '', 'koh-sotin', NULL, NULL),
	(156, 20, 'Tve', '', 'tve', NULL, NULL),
	(157, 20, 'Mohaleap', '', 'mohaleap', NULL, NULL),
	(158, 20, 'Moha Knhoung', '', 'moha-knhoung', NULL, NULL),
	(159, 20, 'Peam Brothnous', '', 'peam-brothnous', NULL, NULL),
	(160, 20, 'Pongro', '', 'pongro', NULL, NULL),
	(161, 20, 'Prek Tanung', '', 'prek-tanung', NULL, NULL),
	(162, 21, 'Baray', '', 'baray', NULL, NULL),
	(163, 21, 'Beung Nay', '', 'beung-nay', NULL, NULL),
	(164, 21, 'Chrey Vean', '', 'chrey-vean', NULL, NULL),
	(165, 21, 'Mean', '', 'mean', NULL, NULL),
	(166, 21, 'Trapeang Preah', '', 'trapeang-preah', NULL, NULL),
	(167, 21, 'Khvet Thum', '', 'khvet-thum', NULL, NULL),
	(168, 21, 'Kor', '', 'kor', NULL, NULL),
	(169, 21, 'Krouch', '', 'krouch', NULL, NULL),
	(170, 21, 'Lvea', '', 'lvea', NULL, NULL),
	(171, 21, 'Prey Chor', '', 'prey-chor', NULL, NULL),
	(172, 21, 'Sor Sen', '', 'sor-sen', NULL, NULL),
	(173, 21, 'Somrorng', '', 'somrorng', NULL, NULL),
	(174, 21, 'Sro Ngae', '', 'sro-ngae', NULL, NULL),
	(175, 21, 'Thma Poun', '', 'thma-poun', NULL, NULL),
	(176, 21, 'Tong Rong', '', 'tong-rong', NULL, NULL),
	(177, 22, 'Baray', '', 'baray', NULL, NULL),
	(178, 22, 'Chibal', '', 'chibal', NULL, NULL),
	(179, 22, 'Khnar Sor', '', 'khnar-sor', NULL, NULL),
	(180, 22, 'Koh Andet', '', 'koh-andet', NULL, NULL),
	(181, 22, 'Mean Chey', '', 'mean-chey', NULL, NULL),
	(182, 22, 'Phteas Kandal', '', 'phteas-kandal', NULL, NULL),
	(183, 22, 'Bram Yam', '', 'bram-yam', NULL, NULL),
	(184, 22, 'Prek Dombok', '', 'prek-dombok', NULL, NULL),
	(185, 22, 'Prek Por', '', 'prek-por', NULL, NULL),
	(186, 22, 'Prek Romdeng', '', 'prek-romdeng', NULL, NULL),
	(187, 22, 'Russey Srok', '', 'russey-srok', NULL, NULL),
	(188, 22, 'Svay Por', '', 'svay-por', NULL, NULL),
	(189, 22, 'Svay Ksach Phnom', '', 'svay-ksach-phnom', NULL, NULL),
	(190, 22, 'Torng Trolach', '', 'torng-trolach', NULL, NULL),
	(191, 23, 'Areak Tnort', '', 'areak-tnort', NULL, NULL),
	(192, 23, 'Dorng Kdar', '', 'dorng-kdar', NULL, NULL),
	(193, 23, 'Kpob Tangoun', '', 'kpob-tangoun', NULL, NULL),
	(194, 23, 'Mesar Chrey', '', 'mesar-chrey', NULL, NULL),
	(195, 23, 'Or Mlou', '', 'or-mlou', NULL, NULL),
	(196, 23, 'Peam Koh Sna', '', 'peam-koh-sna', NULL, NULL),
	(197, 23, 'Preah Andong', '', 'preah-andong', NULL, NULL),
	(198, 23, 'Prek Kork', '', 'prek-kork', NULL, NULL),
	(199, 23, 'Sopheas', '', 'sopheas', NULL, NULL),
	(200, 23, 'Toul Preahkhleang', '', 'toul-preahkhleang', NULL, NULL),
	(201, 23, 'Toul Sombor', '', 'toul-sombor', NULL, NULL),
	(202, 24, 'Batheay', '', 'batheay', NULL, NULL),
	(203, 24, 'Chbar Ampov', '', 'chbar-ampov', NULL, NULL),
	(204, 24, 'Chealea', '', 'chealea', NULL, NULL),
	(205, 24, 'Cheung Prey', '', 'cheung-prey', NULL, NULL),
	(206, 24, 'Me Pring', '', 'me-pring', NULL, NULL),
	(207, 24, 'Phav', '', 'phav', NULL, NULL),
	(208, 24, 'Sambour', '', 'sambour', NULL, NULL),
	(209, 24, 'Sandaek', '', 'sandaek', NULL, NULL),
	(210, 24, 'Tang Krang', '', 'tang-krang', NULL, NULL),
	(211, 24, 'Prasat', '', 'prasat', NULL, NULL),
	(212, 24, 'Tang Krasang', '', 'tang-krasang', NULL, NULL),
	(213, 24, 'Trab Roung', '', 'trab-roung', NULL, NULL),
	(214, 24, 'Tumnob', '', 'tumnob', NULL, NULL),
	(215, 25, 'Bos Khnaor', '', 'bos-khnaor', NULL, NULL),
	(216, 25, 'Chamkar Andoung', '', 'chamkar-andoung', NULL, NULL),
	(217, 25, 'Cheyyou', '', 'cheyyou', NULL, NULL),
	(218, 25, 'Lvea Leu', '', 'lvea-leu', NULL, NULL),
	(219, 25, 'Spueu', '', 'spueu', NULL, NULL),
	(220, 25, 'Svay Teab', '', 'svay-teab', NULL, NULL),
	(221, 25, 'Ta Ong', '', 'ta-ong', NULL, NULL),
	(222, 25, 'Ta Prok', '', 'ta-prok', NULL, NULL),
	(223, 26, 'Khnaor Dambang', '', 'khnaor-dambang', NULL, NULL),
	(224, 26, 'Kouk Rovieng', '', 'kouk-rovieng', NULL, NULL),
	(225, 26, 'Phdau Chum', '', 'phdau-chum', NULL, NULL),
	(226, 26, 'Prey Char', '', 'prey-char', NULL, NULL),
	(227, 26, 'Pring Chrum', '', 'pring-chrum', NULL, NULL),
	(228, 26, 'Sampong Chey', '', 'sampong-chey', NULL, NULL),
	(229, 26, 'Sdaeung Chey', '', 'sdaeung-chey', NULL, NULL),
	(230, 26, 'Soutip', '', 'soutip', NULL, NULL),
	(231, 26, 'Srama', '', 'srama', NULL, NULL),
	(232, 26, 'Trapeang Kor', '', 'trapeang-kor', NULL, NULL),
	(233, 27, 'Char Chhouk', 'ចារឈូក', 'char-chhouk', NULL, NULL),
	(234, 27, 'Daun Peng', 'ដូនពេង', 'daun-peng', NULL, NULL),
	(235, 27, 'Koak Daung', 'គោកដូង', 'koak-daung', NULL, NULL),
	(236, 27, 'Koal', 'គោល', 'koal', NULL, NULL),
	(237, 27, 'Nokor Pheas', 'នគរភាស', 'nokor-pheas', NULL, NULL),
	(238, 27, 'Srae Khvav', 'ស្រែខ្វាវ', 'srae-khvav', NULL, NULL),
	(239, 27, 'Tasoam', 'តាសោម', 'tasoam', NULL, NULL),
	(240, 28, 'Chub Tatrav', 'ជប់តាត្រាវ', 'chub-tatrav', NULL, NULL),
	(241, 28, 'Leang Dai', 'លាងដៃ', 'leang-dai', NULL, NULL),
	(242, 28, 'Peak Snaeng', 'ពាក់ស្នែង', 'peak-snaeng', NULL, NULL),
	(243, 28, 'Svay Chek', 'ស្វាយចេក', 'svay-chek', NULL, NULL),
	(244, 29, 'Khnar Sanday', 'ខ្នារសណ្តាយ', 'khnar-sanday', NULL, NULL),
	(245, 29, 'Khun Ream', 'ឃុនរាម', 'khun-ream', NULL, NULL),
	(246, 29, 'Preak Dak', 'ព្រះដាក់', 'preak-dak', NULL, NULL),
	(247, 29, 'Romchek', 'រំចេក', 'romchek', NULL, NULL),
	(248, 29, 'Run Ta Aek', 'រុនតាឯក', 'run-ta-aek', NULL, NULL),
	(249, 29, 'Tbaeng', 'ត្បែង', 'tbaeng', NULL, NULL),
	(250, 30, 'Anlong Samnor', 'អន្លង់សំណរ', 'anlong-samnor', NULL, NULL),
	(251, 30, 'Chi Kraeng', 'ជីក្រែង', 'chi-kraeng', NULL, NULL),
	(252, 30, 'Kampong Kdei', 'កំពង់ក្តី', 'kampong-kdei', NULL, NULL),
	(253, 30, 'Khvav', 'ខ្វាវ', 'khvav', NULL, NULL),
	(254, 30, 'Koak Thlok Krom', 'គោកធ្លកក្រោម', 'koak-thlok-krom', NULL, NULL),
	(255, 30, 'Koak Thlok Leu', 'គោកធ្លកលើ', 'koak-thlok-leu', NULL, NULL),
	(256, 30, 'Lveng Russei', 'ល្វែងឫស្សី', 'lveng-russei', NULL, NULL),
	(257, 30, 'Pongro Krom', 'ពង្រក្រោម', 'pongro-krom', NULL, NULL),
	(258, 30, 'Pongro Leu', 'ពង្រលើ', 'pongro-leu', NULL, NULL),
	(259, 30, 'Russei Lok', 'ឫស្សីលក', 'russei-lok', NULL, NULL),
	(260, 30, 'Songveuy', 'សង្វើយ', 'songveuy', NULL, NULL),
	(261, 30, 'Spean Tnoat', 'ស្ពានត្នោត', 'spean-tnoat', NULL, NULL),
	(262, 31, 'Chonleas Dai', 'ជន្លាស់ដៃ', 'chonleas-dai', NULL, NULL),
	(263, 31, 'Kampong Thkov', 'កំពង់ថ្កូវ', 'kampong-thkov', NULL, NULL),
	(264, 31, 'Kralanh', 'ក្រឡាញ់', 'kralanh', NULL, NULL),
	(265, 31, 'Krouch Kor', 'ក្រូចគរ', 'krouch-kor', NULL, NULL),
	(266, 31, 'Roang Koar', 'រោងគោ', 'roang-koar', NULL, NULL),
	(267, 31, 'Sambour', 'សំបួរ', 'sambour', NULL, NULL),
	(268, 31, 'Sen Sok', 'សែនសុខ', 'sen-sok', NULL, NULL),
	(269, 31, 'Snoul', 'ស្នួល', 'snoul', NULL, NULL),
	(270, 31, 'Sronal', 'ស្រណាល', 'sronal', NULL, NULL),
	(271, 31, 'Ta An', 'តាអាន', 'ta-an', NULL, NULL),
	(272, 32, 'Sosor Sdom', 'សសរស្តម្', 'sosor-sdom', NULL, NULL),
	(273, 32, 'Daun Keo', 'ដូនកែវ', 'daun-keo', NULL, NULL),
	(274, 32, 'Kdei Run', 'ក្តីរុន', 'kdei-run', NULL, NULL),
	(275, 32, 'Keo Por', 'កែវពណ៌', 'keo-por', NULL, NULL),
	(276, 32, 'Khnat', 'ខ្នាត', 'khnat', NULL, NULL),
	(277, 32, 'Lvea', 'ល្វា', 'lvea', NULL, NULL),
	(278, 32, 'Mukh Paen', 'មុខប៉ែន', 'mukh-paen', NULL, NULL),
	(279, 32, 'Pou Treay', 'ពោធិទ្រាយ', 'pou-treay', NULL, NULL),
	(280, 32, 'Pouk', 'ពួក', 'pouk', NULL, NULL),
	(281, 32, 'Prey Chrouk', 'ព្រៃជ្រូក', 'prey-chrouk', NULL, NULL),
	(282, 32, 'Reul', 'រើស', 'reul', NULL, NULL),
	(283, 32, 'Somroang Yea', 'សំរោងយា', 'somroang-yea', NULL, NULL),
	(284, 32, 'Treu Nhoar', 'ត្រីញ័រ', 'treu-nhoar', NULL, NULL),
	(285, 32, 'Yeang', 'យាង', 'yeang', NULL, NULL),
	(286, 32, 'Tuek Vil', 'ទឹកវិល', 'tuek-vil', NULL, NULL),
	(287, 32, 'Krabei Riel', 'ក្របីរៀល', 'krabei-riel', NULL, NULL),
	(288, 33, 'Bakong', 'បាគង', 'bakong', NULL, NULL),
	(289, 33, 'Balangk', 'បល្ល័ង្គ', 'balangk', NULL, NULL),
	(290, 33, 'Kampong Phluk', 'កំពង់ភ្លុក', 'kampong-phluk', NULL, NULL),
	(291, 33, 'Kantreang', 'កន្ទ្រាំង', 'kantreang', NULL, NULL),
	(292, 33, 'Kandaek', 'កណ្តែក', 'kandaek', NULL, NULL),
	(293, 33, 'Meanchey', 'មានជ័យ', 'meanchey', NULL, NULL),
	(294, 33, 'Rolous', 'រលួស', 'rolous', NULL, NULL),
	(295, 33, 'Trapeang Thom', 'ត្រពាំងធំ', 'trapeang-thom', NULL, NULL),
	(296, 33, 'Ampil', 'អំពិល', 'ampil', NULL, NULL),
	(297, 34, 'Slor Kram', 'ស្លក្រាម', 'slor-kram', NULL, NULL),
	(298, 34, 'Svay Dongkum', 'ស្វាយដង្គំ', 'svay-dongkum', NULL, NULL),
	(299, 34, 'Koak Chork', 'គោកចក', 'koak-chork', NULL, NULL),
	(300, 34, 'Sala Komreuk', 'សាលាកំរើក', 'sala-komreuk', NULL, NULL),
	(301, 34, 'Nokor Thom', 'នគរធំ', 'nokor-thom', NULL, NULL),
	(302, 34, 'Chreav', 'ជ្រាវ', 'chreav', NULL, NULL),
	(303, 34, 'Chong Khneas', 'ចុងឃ្នៀស', 'chong-khneas', NULL, NULL),
	(304, 34, 'Sambour', 'សំបួរ', 'sambour', NULL, NULL),
	(305, 34, 'Seam Reap', 'សៀមរាប', 'seam-reap', NULL, NULL),
	(306, 34, 'Sragnae', 'ស្រង៉ែ', 'sragnae', NULL, NULL),
	(307, 34, 'Ampil', 'អំពិល', 'ampil', NULL, NULL),
	(308, 34, 'Krabei Real', 'ក្របីរៀល', 'krabei-real', NULL, NULL),
	(309, 34, 'Teuk Vil', 'ទឹកវិល', 'teuk-vil', NULL, NULL),
	(310, 35, 'Chan Sor', 'ចាន់ស', 'chan-sor', NULL, NULL),
	(311, 35, 'Dom Daek', 'ដំដែក', 'dom-daek', NULL, NULL),
	(312, 35, 'Danrun', 'ដានរុន', 'danrun', NULL, NULL),
	(313, 35, 'Kampong Khleang', 'កំពង់ឃ្លាំង', 'kampong-khleang', NULL, NULL),
	(314, 35, 'Kean Sangke', 'កៀនសង្កែ', 'kean-sangke', NULL, NULL),
	(315, 35, 'Khchas', 'ខ្ចាស់', 'khchas', NULL, NULL),
	(316, 35, 'Khnar Pou', 'ខ្នារពោធិ៍', 'khnar-pou', NULL, NULL),
	(317, 35, 'Popel', 'ពពេល', 'popel', NULL, NULL),
	(318, 35, 'Samroang', 'សំរោង', 'samroang', NULL, NULL),
	(319, 35, 'Ta Yaek', 'តាយ៉ែក', 'ta-yaek', NULL, NULL),
	(320, 36, 'Chroy Neang Ngoun', 'ជ្រោយនាងងួន', 'chroy-neang-ngoun', NULL, NULL),
	(321, 36, 'Klang Hay', 'ក្លាំងហាយ', 'klang-hay', NULL, NULL),
	(322, 36, 'Tram Sosor', 'ត្រាំសសរ', 'tram-sosor', NULL, NULL),
	(323, 36, 'Moang', 'មោង', 'moang', NULL, NULL),
	(324, 36, 'Brey', 'ប្រីយ៍', 'brey', NULL, NULL),
	(325, 36, 'Slaeng Spean', 'ស្លែងស្ពាន', 'slaeng-spean', NULL, NULL),
	(326, 37, 'Beung Mealea', 'បឹងមាលា', 'beung-mealea', NULL, NULL),
	(327, 37, 'Kantout', 'កន្ទួត', 'kantout', NULL, NULL),
	(328, 37, 'Khnorng Phnum', 'ខ្នងភ្នំ', 'khnorng-phnum', NULL, NULL),
	(329, 37, 'Svay Leu', 'ស្វាយលើ', 'svay-leu', NULL, NULL),
	(330, 37, 'Ta Seam', 'តាសៀម', 'ta-seam', NULL, NULL),
	(331, 38, 'Brasat', 'ប្រាសាទ', 'brasat', NULL, NULL),
	(332, 38, 'Lvea Krang', 'ល្វាក្រាំង', 'lvea-krang', NULL, NULL),
	(333, 38, 'Srae Noy', 'ស្រែណូយ', 'srae-noy', NULL, NULL),
	(334, 38, 'Svay Sor', 'ស្វាយស', 'svay-sor', NULL, NULL),
	(335, 38, 'Varin', 'វ៉ារិន', 'varin', NULL, NULL),
	(336, 39, 'Kantueu Muoy', 'កន្ទឺ ១', 'kantueu-muoy', NULL, NULL),
	(337, 39, 'Kantueu Pir', 'កន្ទឺ ២', 'kantueu-pir', NULL, NULL),
	(338, 39, 'Bay Damram', 'បាយដំរាំ', 'bay-damram', NULL, NULL),
	(339, 39, 'Chheu Teal', '	ឈើទាល', 'chheu-teal', NULL, NULL),
	(340, 39, 'Chaeng Mean Chey', 'ចែងមានជ័យ', 'chaeng-mean-chey', NULL, NULL),
	(341, 39, 'Phnum Sampov', 'ភ្នំសំពៅ', 'phnum-sampov', NULL, NULL),
	(342, 39, 'Snoeng', 'ស្នឹង', 'snoeng', NULL, NULL),
	(343, 39, 'Ta Kream', 'តាគ្រាម', 'ta-kream', NULL, NULL),
	(344, 40, 'Ta Pung', 'តាពូង', 'ta-pung', NULL, NULL),
	(345, 40, 'តាម៉ឺន', 'Ta Meun', '', NULL, NULL),
	(346, 40, 'Ou Ta Ki', 'អូរតាគី', 'ou-ta-ki', NULL, NULL),
	(347, 40, 'Chrey', 'ជ្រៃ', 'chrey', NULL, NULL),
	(348, 40, 'Anlong Run', 'អន្លង់រុន', 'anlong-run', NULL, NULL),
	(349, 40, 'Chrouy Sdau', 'ជ្រោយស្តៅ', 'chrouy-sdau', NULL, NULL),
	(350, 40, 'Boeng Pring', 'បឹងព្រីង', 'boeng-pring', NULL, NULL),
	(351, 40, 'Kouk Khmum', 'គោកឃ្មុំ', 'kouk-khmum', NULL, NULL),
	(352, 40, 'Bansay Traeng', 'បន្សាយត្រែង', 'bansay-traeng', NULL, NULL),
	(353, 40, 'Rung Chrey', 'រូងជ្រៃ', 'rung-chrey', NULL, NULL),
	(354, 41, 'Tuol Ta Aek', 'ទួលតាឯក', 'tuol-ta-aek', NULL, NULL),
	(355, 41, 'Preaek Preah Sdach', 'ព្រែកព្រះស្តេច', 'preaek-preah-sdach', NULL, NULL),
	(356, 41, 'Rotanak', 'រតនៈ', 'rotanak', NULL, NULL),
	(357, 41, 'Chamkar Samraong', 'ចំការសំរោង', 'chamkar-samraong', NULL, NULL),
	(358, 41, 'Sla Kaet', 'ស្លាកែត', 'sla-kaet', NULL, NULL),
	(359, 41, 'Kdol Doun Teav', 'ក្តុលដូនទាវ', 'kdol-doun-teav', NULL, NULL),
	(360, 41, 'Ou Mal', 'អូរម៉ាល់', 'ou-mal', NULL, NULL),
	(361, 41, 'Voat Kor', 'វត្តគរ', 'voat-kor', NULL, NULL),
	(362, 41, 'Ou Char', 'អូរចារ', 'ou-char', NULL, NULL),
	(363, 41, 'Svay Pao', 'ស្វាយប៉ោ', 'svay-pao', NULL, NULL),
	(364, 42, 'Bavel', 'បវេល', 'bavel', NULL, NULL),
	(365, 42, 'Khnach Romeas', 'ខ្នាចរមាស', 'khnach-romeas', NULL, NULL),
	(366, 42, 'Lvea', 'ល្វា', 'lvea', NULL, NULL),
	(367, 42, 'Prey Khpos', 'ព្រៃខ្ពស់', 'prey-khpos', NULL, NULL),
	(368, 42, 'Ampil Pram Daeum', 'អំពិលប្រាំដើម', 'ampil-pram-daeum', NULL, NULL),
	(369, 42, 'Kdol Tahen', 'ក្តុលតាហែន', 'kdol-tahen', NULL, NULL),
	(370, 42, 'Khlang meas', 'ខ្លាំងមាស', 'khlang-meas', NULL, NULL),
	(371, 42, 'Boeng pram', 'បឹងប្រាំ', 'boeng-pram', NULL, NULL),
	(372, 43, 'Preaek Norint', 'ព្រែកនរិន្ទ', 'preaek-norint', NULL, NULL),
	(373, 43, 'Samraong Knong', 'សំរោងក្នុង', 'samraong-knong', NULL, NULL),
	(374, 43, 'Preaek Khpob', 'ព្រែកខ្ពប', 'preaek-khpob', NULL, NULL),
	(375, 43, 'Preaek Luong', 'ព្រែកហ្លួង', 'preaek-luong', NULL, NULL),
	(376, 43, 'Peam Aek', 'ពាមឯក', 'peam-aek', NULL, NULL),
	(377, 43, 'Prey Chas', 'ព្រៃចាស់', 'prey-chas', NULL, NULL),
	(378, 43, 'Kaoh Chiveang Thvang', 'កោះជីវាំង', 'kaoh-chiveang-thvang', NULL, NULL),
	(379, 44, 'Moung', 'មោង', 'moung', NULL, NULL),
	(380, 44, 'Kear', 'គារ', 'kear', NULL, NULL),
	(381, 44, 'Prey Svay', 'ព្រៃស្វាយ', 'prey-svay', NULL, NULL),
	(382, 44, 'Ruessei Krang', 'ឫស្សីក្រាំង', 'ruessei-krang', NULL, NULL),
	(383, 44, 'Chrey', 'ជ្រៃ', 'chrey', NULL, NULL),
	(384, 44, 'Ta Loas', 'តាលាស់', 'ta-loas', NULL, NULL),
	(385, 44, 'Kakaoh', 'កកោះ', 'kakaoh', NULL, NULL),
	(386, 44, 'Prey Touch', 'ព្រៃតូច', 'prey-touch', NULL, NULL),
	(387, 44, 'Robas Mongkol', 'របស់មង្គល', 'robas-mongkol', NULL, NULL),
	(388, 44, 'Break Chek', 'ព្រែកជីក', 'break-chek', NULL, NULL),
	(389, 44, 'Prey Trolach', 'ព្រៃត្រឡាច', 'prey-trolach', NULL, NULL),
	(390, 45, 'Sdau', 'ស្តៅ', 'sdau', NULL, NULL),
	(391, 45, 'Andaeuk Haeb', 'អណ្តើកហែប', 'andaeuk-haeb', NULL, NULL),
	(392, 45, 'Phlov Meas', 'ផ្លូវមាស', 'phlov-meas', NULL, NULL),
	(393, 45, 'Traeng', 'ត្រែង', 'traeng', NULL, NULL),
	(394, 45, 'Reaksmey Sangha', 'រស្មីសង្ហារ', 'reaksmey-sangha', NULL, NULL),
	(395, 46, 'Anlong Vil', 'អន្លង់វិល', 'anlong-vil', NULL, NULL),
	(396, 46, 'Norea', 'នរា', 'norea', NULL, NULL),
	(397, 46, 'Ta Pon', 'តាប៉ុន', 'ta-pon', NULL, NULL),
	(398, 46, 'Roka', 'រកា', 'roka', NULL, NULL),
	(399, 46, 'Kampong Preah', 'កំពង់ព្រះ', 'kampong-preah', NULL, NULL),
	(400, 46, 'Kampong Prieng', 'កំពង់ព្រៀង', 'kampong-prieng', NULL, NULL),
	(401, 46, 'Reang Kesei', 'រាំងកេសី', 'reang-kesei', NULL, NULL),
	(402, 46, 'Ou Dambang Muoy', 'អូរដំបង ១', 'ou-dambang-muoy', NULL, NULL),
	(403, 46, 'Ou Dambang Pir', 'អូរដំបង ២', 'ou-dambang-pir', NULL, NULL),
	(404, 46, 'Vaot Ta Muem', 'វត្តតាមិម', 'vaot-ta-muem', NULL, NULL),
	(405, 47, 'Ta Taok', 'តាតោក', 'ta-taok', NULL, NULL),
	(406, 47, 'Kampong Lpou', 'កំពង់ល្ពៅ', 'kampong-lpou', NULL, NULL),
	(407, 47, 'Ou Samrel', 'អូរសំរិល', 'ou-samrel', NULL, NULL),
	(408, 47, 'Sung', 'ស៊ុង', 'sung', NULL, NULL),
	(409, 47, 'Samlout', 'សំឡូត', 'samlout', NULL, NULL),
	(410, 47, 'Mean Cheay', 'មានជ័យ', 'mean-cheay', NULL, NULL),
	(411, 47, 'Ta Sanh', 'តាសាញ', 'ta-sanh', NULL, NULL),
	(412, 48, 'Sampou Lun', 'សំពៅលូន', 'sampou-lun', NULL, NULL),
	(413, 48, 'Angkor Ban', 'អង្គរបាន', 'angkor-ban', NULL, NULL),
	(414, 48, 'Ta Sda', 'តាសា្ត', 'ta-sda', NULL, NULL),
	(415, 48, 'Santepheap', 'សន្តិភាព', 'santepheap', NULL, NULL),
	(416, 48, 'Serei Maen Cheay', 'សិរីមានជ័យ', 'serei-maen-cheay', NULL, NULL),
	(417, 48, 'Chrey Sema', 'ជ្រៃសីមា', 'chrey-sema', NULL, NULL),
	(418, 49, 'Phnum Proek', 'ភ្នំព្រឹក', 'phnum-proek', NULL, NULL),
	(419, 49, 'Pech Chenda', 'ពេជ្រចិន្តា', 'pech-chenda', NULL, NULL),
	(420, 49, 'Bou', 'បួរ', 'bou', NULL, NULL),
	(421, 49, 'Barang Thleak', 'បារាំងធ្លាក់', 'barang-thleak', NULL, NULL),
	(422, 49, 'Ou Rumduol', 'អូររំដួល', 'ou-rumduol', NULL, NULL),
	(423, 50, 'Kamrieng', 'កំរៀង', 'kamrieng', NULL, NULL),
	(424, 50, 'Boeng Reang', 'បឹងរាំង', 'boeng-reang', NULL, NULL),
	(425, 50, 'Ou Da', 'អូរដា', 'ou-da', NULL, NULL),
	(426, 50, 'Trang', 'ត្រាង', 'trang', NULL, NULL),
	(427, 50, 'Ta Saen', 'តាសែន', 'ta-saen', NULL, NULL),
	(428, 50, 'Ta Krai', 'តាក្រី', 'ta-krai', NULL, NULL),
	(429, 51, 'Thipakdei', 'ធិបតី', 'thipakdei', NULL, NULL),
	(430, 51, 'Koas Krala', 'គាស់ក្រឡ', 'koas-krala', NULL, NULL),
	(431, 51, 'Hab', 'ហប់', 'hab', NULL, NULL),
	(432, 51, 'Preah Phos', 'ព្រះផុស', 'preah-phos', NULL, NULL),
	(433, 51, 'Doun Ba', 'ដូនបា', 'doun-ba', NULL, NULL),
	(434, 51, 'Chhnal Moan', 'ឆ្នាល់មាន់', 'chhnal-moan', NULL, NULL),
	(435, 52, 'Prek chik', 'ព្រែកជីក', 'prek-chik', NULL, NULL),
	(436, 52, 'prey trolach', 'ព្រៃត្រឡាច', 'prey-trolach', NULL, NULL),
	(437, 52, 'Basak', 'បាសាក', 'basak', NULL, NULL),
	(438, 52, 'Mukrea', 'មុគគ្រា', 'mukrea', NULL, NULL),
	(439, 52, 'Sduk Provek', 'ស្តុកផ្រូវិក', 'sduk-provek', NULL, NULL),
	(440, 53, 'Ampov Prey', 'អំពៅព្រៃ', 'ampov-prey', NULL, NULL),
	(441, 53, 'Anlong Romiet', 'អន្លង់រមៀត', 'anlong-romiet', NULL, NULL),
	(442, 53, 'Barku', 'បាគូ', 'barku', NULL, NULL),
	(443, 53, 'Boeng Khyang', 'បឹងខ្យាង', 'boeng-khyang', NULL, NULL),
	(444, 53, 'Cheung Kaeub', 'ជើងកើប', 'cheung-kaeub', NULL, NULL),
	(445, 53, 'Daeum Rues', 'ដើមឫស', 'daeum-rues', NULL, NULL),
	(446, 53, 'Kandaok', 'កណ្តោក', 'kandaok', NULL, NULL),
	(447, 53, 'Thmei', 'ថ្មី', 'thmei', NULL, NULL),
	(448, 53, 'Kouk Trab', 'គោកត្រប់', 'kouk-trab', NULL, NULL),
	(449, 53, 'Preah Putth', 'ព្រះពុទ្ធ', 'preah-putth', NULL, NULL),
	(450, 53, 'Preaek Roka', 'ព្រែករកា', 'preaek-roka', NULL, NULL),
	(451, 53, 'Preaek Slaeng', 'ព្រែកស្លែង', 'preaek-slaeng', NULL, NULL),
	(452, 53, 'Roka', 'រកា', 'roka', NULL, NULL),
	(453, 53, 'Roleang Kaen', 'រលាំងកែន', 'roleang-kaen', NULL, NULL),
	(454, 53, 'Siem Reab', 'សៀមរាប', 'siem-reab', NULL, NULL),
	(455, 53, 'Tbaeng', 'ត្បែងទៀន', 'tbaeng', NULL, NULL),
	(456, 53, 'Trapeang Veaeng', 'ត្រពាំងវែង', 'trapeang-veaeng', NULL, NULL),
	(457, 53, 'Trea', 'ទ្រា', 'trea', NULL, NULL),
	(458, 54, 'Chheu Kmau', 'ឈើខ្មៅ', 'chheu-kmau', NULL, NULL),
	(459, 54, 'Chrouy Ta Kae', 'ជ្រោយតាកែវ', 'chrouy-ta-kae', NULL, NULL),
	(460, 54, 'Kampong Kong', 'កំពង់កុង', 'kampong-kong', NULL, NULL),
	(461, 54, 'Kaoh Thum Ka', 'កោះធំ ក', 'kaoh-thum-ka', NULL, NULL),
	(462, 54, 'Kaoh Thum Kha', 'កោះធំ ខ', 'kaoh-thum-kha', NULL, NULL),
	(463, 54, 'Leuk Daek', 'លើកដែក', 'leuk-daek', NULL, NULL),
	(464, 54, 'Pouthi Ban', 'ពោធិ៍បាន', 'pouthi-ban', NULL, NULL),
	(465, 54, 'Prea​ek Chrey', 'ព្រែកជ្រៃ', 'prea-ek-chrey', NULL, NULL),
	(466, 54, 'Preaek Sdei', 'ព្រែកស្ដី', 'preaek-sdei', NULL, NULL),
	(467, 54, 'Preaek Thmei', 'ព្រែកថ្មី', 'preaek-thmei', NULL, NULL),
	(468, 54, 'Sampeou Poun', 'សំពៅពូន', 'sampeou-poun', NULL, NULL),
	(469, 55, 'Praek Anchanh', 'ព្រែកអញ្ចាញ', 'praek-anchanh', NULL, NULL),
	(470, 55, 'Praek Dombong', 'ព្រែកដំបង', 'praek-dombong', NULL, NULL),
	(471, 55, 'Rokakoang Ti Mouy', 'រកាកោងទី១', 'rokakoang-ti-mouy', NULL, NULL),
	(472, 55, 'Rokakoang Ti Pir', 'រកាកោងទី២', 'rokakoang-ti-pir', NULL, NULL),
	(473, 55, 'Russei Chroay', 'ឫស្សីជ្រោយ', 'russei-chroay', NULL, NULL),
	(474, 55, 'Sambour Meas', 'សំបួរមាស', 'sambour-meas', NULL, NULL),
	(475, 55, 'Svay Ampear', 'ស្វាយអំពារ', 'svay-ampear', NULL, NULL),
	(476, 56, 'Khpob', 'ខ្ពប', 'khpob', NULL, NULL),
	(477, 56, 'Kaoh Anlong Chen', 'កោះអន្លង់ចិន', 'kaoh-anlong-chen', NULL, NULL),
	(478, 56, 'Kaoh Khael', 'កោះខែល', 'kaoh-khael', NULL, NULL),
	(479, 56, 'Kaoh Khsach Tonlea', 'កោះខ្សាច់ទន្លា', 'kaoh-khsach-tonlea', NULL, NULL),
	(480, 56, 'Krang Yov', 'ក្រាំងយ៉ូវ', 'krang-yov', NULL, NULL),
	(481, 56, 'Prasat', 'ប្រាសាទ', 'prasat', NULL, NULL),
	(482, 56, 'Preaek Ambel', 'ព្រែអំបិល', 'preaek-ambel', NULL, NULL),
	(483, 56, 'Preaek Koy', 'ព្រែកគយ', 'preaek-koy', NULL, NULL),
	(484, 56, 'Roka Khpos', 'រកាខ្ពស់', 'roka-khpos', NULL, NULL),
	(485, 56, 'Sa ang Phnum', 'ស្អាងភ្នំ', 'sa-ang-phnum', NULL, NULL),
	(486, 56, 'Setbou', 'សិត្បូ', 'setbou', NULL, NULL),
	(487, 56, 'Svay Prateal', 'ស្វាយប្រទាល', 'svay-prateal', NULL, NULL),
	(488, 56, 'Svay Rolum', 'ស្វាយរលំ', 'svay-rolum', NULL, NULL),
	(489, 56, 'Ta Lon', 'តាលន់', 'ta-lon', NULL, NULL),
	(490, 56, 'Traeuy Sla', 'ត្រើយស្លា', 'traeuy-sla', NULL, NULL),
	(491, 56, 'Tuek Vil', 'ទឹកវិល', 'tuek-vil', NULL, NULL),
	(492, 57, 'Kampong Phnum', 'កំពង់ភ្នំ', 'kampong-phnum', NULL, NULL),
	(493, 57, 'K am Samnar', 'ក្អមសំណ', 'k-am-samnar', NULL, NULL),
	(494, 57, 'Khpob Ateav', 'ខ្ពបអាទាវ', 'khpob-ateav', NULL, NULL),
	(495, 57, 'Peam Reang ', 'ពាមរាំង', 'peam-reang', NULL, NULL),
	(496, 57, 'Preaek Dach', 'ព្រែកដាច់', 'preaek-dach', NULL, NULL),
	(497, 57, 'Preaek Tonloab', 'ព្រែកទន្លាប់', 'preaek-tonloab', NULL, NULL),
	(498, 57, 'Sandar', 'សណ្ដារ', 'sandar', NULL, NULL),
	(499, 58, 'Ta Kdol', 'តាក្ដុល', 'ta-kdol', NULL, NULL),
	(500, 58, 'Prek Ruessey', 'ព្រែកឫស្សី', 'prek-ruessey', NULL, NULL),
	(501, 58, 'Doeum Mien', 'ដើមមៀន', 'doeum-mien', NULL, NULL),
	(502, 58, 'Ta Khmao', 'តាខ្មៅ', 'ta-khmao', NULL, NULL),
	(503, 58, 'Prek Ho', 'ព្រែកហូរ', 'prek-ho', NULL, NULL),
	(504, 58, 'Kampong Samnanh', 'កំពង់សំណាញ់', 'kampong-samnanh', NULL, NULL),
	(505, 58, 'Svay Rolum', 'ស្វាយរលំ', 'svay-rolum', NULL, NULL),
	(506, 58, 'Setbou', 'សិត្បូ', 'setbou', NULL, NULL),
	(507, 58, 'Roka Kpos', 'រកាខ្ពស់', 'roka-kpos', NULL, NULL),
	(508, 58, 'Khosh Anlong Chien', 'កោះអន្លង់ចិន', 'khosh-anlong-chien', NULL, NULL),
	(509, 59, 'Banteay Daek', 'បន្ទាយដែក', 'banteay-daek', NULL, NULL),
	(510, 59, 'Chheu Teal', 'ឈើទាល', 'chheu-teal', NULL, NULL),
	(511, 59, 'Dei Edth', 'ដីឥដ្ឋ', 'dei-edth', NULL, NULL),
	(512, 59, 'Kampong Svay', 'កំពង់ស្វាយ', 'kampong-svay', NULL, NULL),
	(513, 59, 'Kokir', 'គគីរ', 'kokir', NULL, NULL),
	(514, 59, 'Kokir Thum', 'គគីរធំ', 'kokir-thum', NULL, NULL),
	(515, 59, 'Phum Thum', 'ភូមិធំ', 'phum-thum', NULL, NULL),
	(516, 59, 'Samraong Thum', 'សំរោងធំ', 'samraong-thum', NULL, NULL),
	(517, 60, 'Chhveang', 'ឈ្វាំង', 'chhveang', NULL, NULL),
	(518, 60, 'Chrey Loas', 'ជ្រៃលាស់', 'chrey-loas', NULL, NULL),
	(519, 60, 'Kampong Luong', 'កំពង់ហ្លួង', 'kampong-luong', NULL, NULL),
	(520, 60, 'Kampong Os', 'កំពង់អុស', 'kampong-os', NULL, NULL),
	(521, 60, 'Kaoh Chen', 'កោះចិន', 'kaoh-chen', NULL, NULL),
	(522, 60, 'Phnum Bat', 'ភ្នំបាត', 'phnum-bat', NULL, NULL),
	(523, 60, 'Ponhea Lueu', 'ពញាឮ', 'ponhea-lueu', NULL, NULL),
	(524, 60, 'Preaek Ta Teaen', 'ព្រែកតាទែន', 'preaek-ta-teaen', NULL, NULL),
	(525, 60, 'Vihear Luong', 'ផ្សារដែក', 'vihear-luong', NULL, NULL),
	(526, 60, 'Tumnob Thum', 'ទំនប់ធំ', 'tumnob-thum', NULL, NULL),
	(527, 60, 'Vihear Luong', 'វិហារហ្លួង', 'vihear-luong', NULL, NULL),
	(528, 61, 'Ariyaksatr', 'អរិយក្សត្រ', 'ariyaksatr', NULL, NULL),
	(529, 61, 'Barong', 'បារុង', 'barong', NULL, NULL),
	(530, 61, 'Beung Krum', 'បឹងគ្រំ', 'beung-krum', NULL, NULL),
	(531, 61, 'Koh Keo', 'កោះកែវ', 'koh-keo', NULL, NULL),
	(532, 61, 'Koh Reah', 'កោះរះ', 'koh-reah', NULL, NULL),
	(533, 61, 'Lvea Sor', 'ល្វាសរ', 'lvea-sor', NULL, NULL),
	(534, 61, 'Peam Okhna Ong', 'ពាមឧកញ៉ាអុង', 'peam-okhna-ong', NULL, NULL),
	(535, 61, 'Phum Thom', 'ភូមិធំ', 'phum-thom', NULL, NULL),
	(536, 61, 'Praek Kmeng', 'ព្រែកក្មេង', 'praek-kmeng', NULL, NULL),
	(537, 61, 'Praek Rey', 'ព្រែករៃ', 'praek-rey', NULL, NULL),
	(538, 61, 'Praek Russei', 'ព្រែកឫស្សី', 'praek-russei', NULL, NULL),
	(539, 61, 'Sombour', 'សំបួរ', 'sombour', NULL, NULL),
	(540, 61, 'Sarikakeo', 'សារិកាកែវ', 'sarikakeo', NULL, NULL),
	(541, 61, 'Thma Kor', 'ថ្មគរ', 'thma-kor', NULL, NULL),
	(542, 61, 'Teuk Khleang', 'ទឹកឃ្លាំង', 'teuk-khleang', NULL, NULL),
	(543, 62, 'Bak Dav', 'បាក់ដាវ', 'bak-dav', NULL, NULL),
	(544, 62, 'Chey Thum', 'ជ័យធំ', 'chey-thum', NULL, NULL),
	(545, 62, 'Kampong Chamlang', 'កំពង់ចំលង', 'kampong-chamlang', NULL, NULL),
	(546, 62, 'Kaoh Chouram', 'កោះចូរ៉ាម', 'kaoh-chouram', NULL, NULL),
	(547, 62, 'Kaoh Oknha Tei', 'កោះឧកញ៉ាតី', 'kaoh-oknha-tei', NULL, NULL),
	(548, 62, 'Preah Prasab', 'ព្រះប្រសប់', 'preah-prasab', NULL, NULL),
	(549, 62, 'Preaek Ampil', 'ព្រែកអំពិល', 'preaek-ampil', NULL, NULL),
	(550, 62, '	Preaek Luong', 'ព្រែកលួង', 'preaek-luong', NULL, NULL),
	(551, 62, 'Preaek Ta Kov', 'ព្រែកតាកូវ', 'preaek-ta-kov', NULL, NULL),
	(552, 62, 'Preaek Ta Meak', 'ព្រែកតាមាក់', 'preaek-ta-meak', NULL, NULL),
	(553, 62, 'Puk Ruessei', 'ពុកឫស្សី', 'puk-ruessei', NULL, NULL),
	(554, 62, 'Roka Chonlueng', 'រកាជន្លឹង', 'roka-chonlueng', NULL, NULL),
	(555, 62, 'Sanlung', 'សន្លុង', 'sanlung', NULL, NULL),
	(556, 62, 'Sithor', 'ស៊ីធរ', 'sithor', NULL, NULL),
	(557, 62, 'Svay Chrum', 'ស្វាយជ្រុំ', 'svay-chrum', NULL, NULL),
	(558, 62, 'Svay Romiet', 'ស្វាយរមៀត', 'svay-romiet', NULL, NULL),
	(559, 62, 'Ta Aek', 'តាឯក', 'ta-aek', NULL, NULL),
	(560, 62, 'Vihear Suork', 'វិហារសួគ៌', 'vihear-suork', NULL, NULL),
	(561, 88, 'Bak Sna', 'បាក់ស្នា', 'bak-sna', NULL, NULL),
	(562, 88, 'Ballangk', 'បល្ល័ង្ក', 'ballangk', NULL, NULL),
	(563, 88, 'Baray', 'បារាយណ៍', 'baray', NULL, NULL),
	(564, 88, 'Boeng', 'បឹង', 'boeng', NULL, NULL),
	(565, 88, 'Chaeung Daeung', 'ចើងដើង', 'chaeung-daeung', NULL, NULL),
	(566, 88, 'Chraneang', 'ច្រនាង', 'chraneang', NULL, NULL),
	(567, 88, 'Chhuk Khsach', 'ឈូកខ្សាច់', 'chhuk-khsach', NULL, NULL),
	(568, 88, 'Chong Doung', 'ចុងដូង', 'chong-doung', NULL, NULL),
	(569, 88, 'Chrolong', 'ជ្រលង', 'chrolong', NULL, NULL),
	(570, 88, 'Kokir Thum ', 'គគីធំ', 'kokir-thum', NULL, NULL),
	(571, 88, 'Krava', 'ក្រវ៉ា', 'krava', NULL, NULL),
	(572, 88, 'Andoung Pou', 'អណ្ដូងពោធិ៍', 'andoung-pou', NULL, NULL),
	(573, 88, 'Pongro', 'ពង្រ', 'pongro', NULL, NULL),
	(574, 88, 'Sou Young', 'សូយោង', 'sou-young', NULL, NULL),
	(575, 88, 'Sralau', 'ស្រឡៅ', 'sralau', NULL, NULL),
	(576, 88, 'Svay Phleung', 'ស្វាយភ្លើង', 'svay-phleung', NULL, NULL),
	(577, 88, 'Tnaot Chum', 'ត្នោតជុំ', 'tnaot-chum', NULL, NULL),
	(578, 88, 'Triel', 'ទ្រៀល', 'triel', NULL, NULL),
	(579, 89, 'Damrei Choan Khla', 'ដំរីជាន់ខ្លា', 'damrei-choan-khla', NULL, NULL),
	(580, 89, 'Kampong Thum', 'កំពង់ធំ', 'kampong-thum', NULL, NULL),
	(581, 89, 'Kampong Roteh', 'កំពង់រទេះ', 'kampong-roteh', NULL, NULL),
	(582, 89, 'Ou Kanthor', 'អូរកន្ធរ', 'ou-kanthor', NULL, NULL),
	(583, 89, 'Kampong', 'កំពង់ក្របៅ', 'kampong', NULL, NULL),
	(584, 89, 'Prey Ta Hu', 'ព្រៃតាហ៊ូ', 'prey-ta-hu', NULL, NULL),
	(585, 89, 'Achar Leak', 'អាចារ្យលាក់', 'achar-leak', NULL, NULL),
	(586, 89, 'Srayov', 'ស្រយ៉ូវ', 'srayov', NULL, NULL),
	(587, 90, 'Chheu Teal ', 'ឈើទាល', 'chheu-teal', NULL, NULL),
	(588, 90, 'Dang Kambet', 'ដងកាំបិត', 'dang-kambet', NULL, NULL),
	(589, 90, 'Klaeng ', 'ក្លែង', 'klaeng', NULL, NULL),
	(590, 90, 'Mean Rith', 'មានរិទ្ធ', 'mean-rith', NULL, NULL),
	(591, 90, 'Mean Chey', 'មានជ័យ', 'mean-chey', NULL, NULL),
	(592, 90, 'Ngan ', 'ងន', 'ngan', NULL, NULL),
	(593, 90, 'Sandan', 'សណ្ដាន់', 'sandan', NULL, NULL),
	(594, 90, 'Sochet', 'សុចិត្រ', 'sochet', NULL, NULL),
	(595, 90, 'Tum Ring', 'ទំរីង', 'tum-ring', NULL, NULL),
	(596, 91, 'Banteay Stoung', 'បន្ទាយស្ទោង', 'banteay-stoung', NULL, NULL),
	(597, 91, 'Chamna Kraom', 'ចំណាក្រោម', 'chamna-kraom', NULL, NULL),
	(598, 91, 'Chamna Leu', 'ចំណាលើ', 'chamna-leu', NULL, NULL),
	(599, 91, 'Kampong Chen Cheung', 'កំពង់ចិនជើង', 'kampong-chen-cheung', NULL, NULL),
	(600, 91, 'Msa Krang', 'ម្សាក្រង', 'msa-krang', NULL, NULL),
	(601, 91, 'Peam Bang', 'ពាមបាង', 'peam-bang', NULL, NULL),
	(602, 91, 'Pralay', 'ប្រឡាយ', 'pralay', NULL, NULL),
	(603, 91, 'Preah Damrei', 'ព្រះដំរី', 'preah-damrei', NULL, NULL),
	(604, 91, 'Rung Roeang', 'រុងរឿង', 'rung-roeang', NULL, NULL),
	(605, 91, 'Samprouch', 'សំព្រោជ', 'samprouch', NULL, NULL),
	(606, 91, 'Trea', 'ទ្រា', 'trea', NULL, NULL),
	(607, 92, 'Doung ', 'ដូង', 'doung', NULL, NULL),
	(608, 92, 'Kraya ', 'ក្រយា', 'kraya', NULL, NULL),
	(609, 92, 'Phan Nheum', 'ផាន់ញើម', 'phan-nheum', NULL, NULL),
	(610, 92, 'Sakream ', 'សាគ្រាម', 'sakream', NULL, NULL),
	(611, 92, 'Sala Visai', 'សាលាវិស័យ', 'sala-visai', NULL, NULL),
	(612, 92, 'Sameakki', 'សាមគ្គី', 'sameakki', NULL, NULL),
	(613, 92, 'Tuol Kreul', 'ទួលគ្រើល', 'tuol-kreul', NULL, NULL),
	(614, 93, 'Boeng Lvea', 'បឹងល្វា', 'boeng-lvea', NULL, NULL),
	(615, 93, 'Chroab ', 'ជ្រាប់', 'chroab', NULL, NULL),
	(616, 93, 'Kampong Thma ', 'កំពង់ថ្ម', 'kampong-thma', NULL, NULL),
	(617, 93, '	Kakaoh ', 'កកោះ', 'kakaoh', NULL, NULL),
	(618, 93, 'Kraya ', 'ក្រយា', 'kraya', NULL, NULL),
	(619, 93, 'Pnov ', 'ព្នៅ', 'pnov', NULL, NULL),
	(620, 93, 'Prasat ', 'ប្រាសាទ', 'prasat', NULL, NULL),
	(621, 93, 'Tang Krasang', 'តាំងក្រសាំង', 'tang-krasang', NULL, NULL),
	(622, 93, 'Ti Pou', 'ទីពោ', 'ti-pou', NULL, NULL),
	(623, 93, 'Tboung Krapeu', 'ត្បូងក្រពើ', 'tboung-krapeu', NULL, NULL),
	(624, 94, 'Chhuk', 'ឈូក', 'chhuk', NULL, NULL),
	(625, 94, 'Koul', 'គោល', 'koul', NULL, NULL),
	(626, 94, 'Sambour', 'សំបូរណ៍', 'sambour', NULL, NULL),
	(627, 94, 'Sraeung', 'ស្រើង', 'sraeung', NULL, NULL),
	(628, 94, 'Tang Krasau', 'តាំងក្រសៅ', 'tang-krasau', NULL, NULL),
	(629, 95, 'Chey', 'ជ័យ', 'chey', NULL, NULL),
	(630, 95, 'Damrei Slab', 'ដំរីស្លាប់', 'damrei-slab', NULL, NULL),
	(631, 95, 'Kampong Kou', 'កំពង់គោ', 'kampong-kou', NULL, NULL),
	(632, 95, 'Kampong Svay', 'កំពង់ស្វាយ', 'kampong-svay', NULL, NULL),
	(633, 95, 'Nipech', 'នីពេជ', 'nipech', NULL, NULL),
	(634, 95, 'Phat Sanday', 'ផាត់សណ្ដាយ', 'phat-sanday', NULL, NULL),
	(635, 95, 'San Kor', 'សាន់គ', 'san-kor', NULL, NULL),
	(636, 95, 'Tbaeng', 'ត្បែង', 'tbaeng', NULL, NULL),
	(637, 95, 'Trapeang', 'ត្រពាំងឫស្សី', 'trapeang', NULL, NULL),
	(638, 95, 'Kdei Doung', 'ក្ដីដូង', 'kdei-doung', NULL, NULL),
	(639, 95, 'Prey Kuy', 'ព្រៃគុយ', 'prey-kuy', NULL, NULL),
	(640, 114, 'Chhlong', 'ឆ្លូង', 'chhlong', NULL, NULL),
	(641, 114, 'Domrei Phong', 'ដំរីផុង', 'domrei-phong', NULL, NULL),
	(642, 114, 'Han Chey', 'ហាន់ជ័យ', 'han-chey', NULL, NULL),
	(643, 114, 'Kampong Domrei', 'កំពង់ដំរី', 'kampong-domrei', NULL, NULL),
	(644, 114, 'Kanhchor', 'កញ្ជរ', 'kanhchor', NULL, NULL),
	(645, 114, 'Ksach Andaet', 'ខ្សាច់អណ្ដែត', 'ksach-andaet', NULL, NULL),
	(646, 114, 'Pongro', 'ពង្រ', 'pongro', NULL, NULL),
	(647, 114, 'Praek Samann', 'ព្រែកសាម៉ាន់', 'praek-samann', NULL, NULL),
	(648, 115, 'Kantout', 'កន្ទួត', 'kantout', NULL, NULL),
	(649, 115, 'Thma Andeuk', 'ថ្មអណ្តើក', 'thma-andeuk', NULL, NULL),
	(650, 115, 'Koh Chraeng', 'កោះច្រែង', 'koh-chraeng', NULL, NULL),
	(651, 115, 'Sambok', 'សំបុក', 'sambok', NULL, NULL),
	(652, 115, 'Kou Lorb', 'គោលាប់', 'kou-lorb', NULL, NULL),
	(653, 115, 'Thmei', 'ថ្មី', 'thmei', NULL, NULL),
	(654, 115, 'Dar', 'ដា', 'dar', NULL, NULL),
	(655, 115, 'Bos Leav', 'បុសលាវ', 'bos-leav', NULL, NULL),
	(656, 115, 'Changkrorng', 'ចង្ក្រង់', 'changkrorng', NULL, NULL),
	(657, 115, 'Thma Krae', 'ថ្មគ្រែ', 'thma-krae', NULL, NULL),
	(658, 116, 'Koh Trorng', 'កោះត្រង់', 'koh-trorng', NULL, NULL),
	(659, 116, 'Krokor', 'ក្រកូរ', 'krokor', NULL, NULL),
	(660, 116, 'Kratie', 'ក្រចេះ', 'kratie', NULL, NULL),
	(661, 116, 'Ou Russei', 'អូរឬស្សី', 'ou-russei', NULL, NULL),
	(662, 116, 'Roka Kandal', 'រកាកណ្តាល', 'roka-kandal', NULL, NULL),
	(663, 117, 'Kbal Domrei', 'ក្បាលដំរី', 'kbal-domrei', NULL, NULL),
	(664, 117, 'Koh Knhae', 'កោះខ្ញែរ', 'koh-knhae', NULL, NULL),
	(665, 117, 'Ou Kreang', 'អូរគ្រៀង', 'ou-kreang', NULL, NULL),
	(666, 117, 'Rolous Meanchey', 'រលួសមានជ័យ', 'rolous-meanchey', NULL, NULL),
	(667, 117, 'Kampong Cham', 'កំពង់ចាម', 'kampong-cham', NULL, NULL),
	(668, 117, 'Beung Char', 'បឹងចារ', 'beung-char', NULL, NULL),
	(669, 117, 'Sombo', 'សំបូរ', 'sombo', NULL, NULL),
	(670, 117, 'Sandann', 'សណ្តាន់', 'sandann', NULL, NULL),
	(671, 117, 'Srae Chis', 'ស្រែជិះ', 'srae-chis', NULL, NULL),
	(672, 117, 'Vadhnak', 'វឌ្ឍនៈ', 'vadhnak', NULL, NULL),
	(673, 118, 'Chambok', 'ចំបក់', 'chambok', NULL, NULL),
	(674, 118, 'Chroy Banteay', 'ជ្រោយបន្ទាយ', 'chroy-banteay', NULL, NULL),
	(675, 118, 'Kampong Kor', 'កំពង់គរ', 'kampong-kor', NULL, NULL),
	(676, 118, 'Praek Brosop', 'ព្រែកប្រសព្', 'praek-brosop', NULL, NULL),
	(677, 118, 'Russei Keo', 'ឫស្សីកែវ', 'russei-keo', NULL, NULL),
	(678, 118, 'Soab', 'សោប', 'soab', NULL, NULL),
	(679, 118, 'Tamao', 'តាម៉ៅ', 'tamao', NULL, NULL),
	(680, 119, 'Khseum', 'ឃ្សឹម', 'khseum', NULL, NULL),
	(681, 119, 'Pir Thnou', 'ពីរធ្នូ', 'pir-thnou', NULL, NULL),
	(682, 119, 'Snoul', 'ស្នួល', 'snoul', NULL, NULL),
	(683, 119, 'Srae Char', 'ស្រែចារ', 'srae-char', NULL, NULL),
	(684, 119, 'Svay Chreas', 'ស្វាយជ្រះ', 'svay-chreas', NULL, NULL),
	(685, 133, 'Sa ang', 'ស្អាង', 'sa-ang', NULL, NULL),
	(686, 133, 'Tor Sou', 'តស៊ូ', 'tor-sou', NULL, NULL),
	(687, 133, 'Kchorng', 'ខ្យង', 'kchorng', NULL, NULL),
	(688, 133, 'Chrach', 'ច្រាច់', 'chrach', NULL, NULL),
	(689, 133, 'Thmea', 'ធ្មា', 'thmea', NULL, NULL),
	(690, 133, 'Putrea', 'ពុទ្រា', 'putrea', NULL, NULL),
	(691, 134, 'ស្រអែម', 'ជាំក្សាន្ត', '', NULL, NULL),
	(692, 134, 'Teuk Krahorm', 'ទឹកក្រហម', 'teuk-krahorm', NULL, NULL),
	(693, 134, 'Pring Thom', 'ព្រីងធំ', 'pring-thom', NULL, NULL),
	(694, 134, 'Romdoh Srae', 'រំដោះស្រែ', 'romdoh-srae', NULL, NULL),
	(695, 134, 'Yeang', 'យាង', 'yeang', NULL, NULL),
	(696, 134, 'Kantout', 'កន្ទួត', 'kantout', NULL, NULL),
	(697, 134, 'Sraem', 'ស្រអែម', 'sraem', NULL, NULL),
	(698, 134, 'Morodok', 'មរតក', 'morodok', NULL, NULL),
	(699, 135, 'Robeab', 'របៀប', 'robeab', NULL, NULL),
	(700, 135, 'Reaksmey', 'រស្មី', 'reaksmey', NULL, NULL),
	(701, 135, 'Rohas', 'រហ័ស', 'rohas', NULL, NULL),
	(702, 135, 'Rong Reung', 'រុងរឿង', 'rong-reung', NULL, NULL),
	(703, 135, 'Rik Reay', 'រីករាយ', 'rik-reay', NULL, NULL),
	(704, 135, 'Rous Roan', 'រួសរាន់', 'rous-roan', NULL, NULL),
	(705, 135, 'Ratanak', 'រតនៈ', 'ratanak', NULL, NULL),
	(706, 135, 'Reab Roay', 'រៀបរយ', 'reab-roay', NULL, NULL),
	(707, 135, 'Reaksa', 'រក្សា', 'reaksa', NULL, NULL),
	(708, 135, 'Romdors', 'រំដោះ', 'romdors', NULL, NULL),
	(709, 135, 'Rumtum', 'រមទម', 'rumtum', NULL, NULL),
	(710, 135, 'Romniy', 'រម្មណីយ', 'romniy', NULL, NULL),
	(711, 136, 'Ro ang', 'រអាង', 'ro-ang', NULL, NULL),
	(712, 136, 'Phnom Tbeng Mouy', 'ភ្នំត្បែងមួយ', 'phnom-tbeng-mouy', NULL, NULL),
	(713, 136, 'Sdao', 'ស្តៅ', 'sdao', NULL, NULL),
	(714, 136, 'Ranakseh', 'រណសិរ្ស', 'ranakseh', NULL, NULL),
	(715, 136, 'Chomreun', 'ចំរើន', 'chomreun', NULL, NULL),
	(716, 137, 'Chhaeb Mouy', 'ឆែបមួយ', 'chhaeb-mouy', NULL, NULL),
	(717, 137, 'Chhaeb Pir', 'ឆែបពីរ', 'chhaeb-pir', NULL, NULL),
	(718, 137, 'Sangke Mouy', 'សង្កែមួយ', 'sangke-mouy', NULL, NULL),
	(719, 137, 'Sangke Pir', 'សង្កែពីរ', 'sangke-pir', NULL, NULL),
	(720, 137, 'Mlouprey Mouy', 'ម្លូព្រៃមួយ', 'mlouprey-mouy', NULL, NULL),
	(721, 137, 'Mlouprey Pir', 'ម្លូព្រៃពីរ', 'mlouprey-pir', NULL, NULL),
	(722, 137, 'Kampong Sralao Mouy', 'កំពង់ស្រឡៅមួយ', 'kampong-sralao-mouy', NULL, NULL),
	(723, 137, 'Kampong Sralao Pir', 'កំពង់ស្រឡៅពីរ', 'kampong-sralao-pir', NULL, NULL),
	(724, 138, 'Kulen Tbong', 'គូលែនត្បូង', 'kulen-tbong', NULL, NULL),
	(725, 138, 'Kulen Cheung', 'គូលែនជើង', 'kulen-cheung', NULL, NULL),
	(726, 138, 'Thmei', 'ថ្មី', 'thmei', NULL, NULL),
	(727, 138, 'Phnom Penh', 'ភ្នំពេញ', 'phnom-penh', NULL, NULL),
	(728, 138, 'Phnom Tbeng Pir', 'ភ្នំត្បែងពីរ', 'phnom-tbeng-pir', NULL, NULL),
	(729, 138, 'Sroyong', 'ស្រយង់', 'sroyong', NULL, NULL),
	(730, 139, 'Kompong bronouk', 'កំពង់ប្រណោក', 'kompong-bronouk', NULL, NULL),
	(731, 139, 'Bal Hal', 'ប៉ាលហាល', 'bal-hal', NULL, NULL),
	(732, 139, 'Chhean Mukh', 'ឈានមុខ', 'chhean-mukh', NULL, NULL),
	(733, 139, 'Pou', 'ពោធិ៍', 'pou', NULL, NULL),
	(734, 139, 'Bromeru', 'ប្រមេរុ', 'bromeru', NULL, NULL),
	(735, 139, 'Preah Khleang', 'ព្រះឃ្លាំង', 'preah-khleang', NULL, NULL),
	(736, 177, 'Komphun', 'កំភុន', 'komphun', NULL, NULL),
	(737, 177, 'Kbal Romeas', 'ក្បាលរមាស', 'kbal-romeas', NULL, NULL),
	(738, 177, 'Phluk', 'ភ្លុក', 'phluk', NULL, NULL),
	(739, 177, 'Sam Khouy', 'សាមឃួយ', 'sam-khouy', NULL, NULL),
	(740, 177, 'Sdau', 'ស្ដៅ', 'sdau', NULL, NULL),
	(741, 177, 'Srae Kor', 'ស្រែគរ', 'srae-kor', NULL, NULL),
	(742, 177, 'Ta Lat', 'តាឡាត', 'ta-lat', NULL, NULL),
	(743, 178, 'Koh Preah', 'កោះព្រះ', 'koh-preah', NULL, NULL),
	(744, 178, 'Koh Sompeay', 'កោះសំពាយ', 'koh-sompeay', NULL, NULL),
	(745, 178, 'Koh Srolay', 'កោះស្រឡាយ', 'koh-srolay', NULL, NULL),
	(746, 178, 'Ou Mreah', 'អូរម្រះ', 'ou-mreah', NULL, NULL),
	(747, 178, 'Ou Russei Kandal', 'អូរឫស្សីកណ្តាល', 'ou-russei-kandal', NULL, NULL),
	(748, 178, 'Siem Bouk', 'សៀមបូក', 'siem-bouk', NULL, NULL),
	(749, 178, 'Srae Krasang', 'ស្រែក្រសាំង', 'srae-krasang', NULL, NULL),
	(750, 178, 'Praek Meas', 'ព្រែកមាស', 'praek-meas', NULL, NULL),
	(751, 178, 'Sekong', 'សេកុង', 'sekong', NULL, NULL),
	(752, 178, 'Santipheap', 'សន្តិភាព', 'santipheap', NULL, NULL),
	(753, 178, 'Srae Sombo', 'ស្រែសំបូរ', 'srae-sombo', NULL, NULL),
	(754, 178, 'Thma Keo', 'ថ្មកែវ', 'thma-keo', NULL, NULL),
	(755, 179, 'Anlong Phe', 'អន្លង់ភេ', 'anlong-phe', NULL, NULL),
	(756, 179, 'Chomkar Leu', 'ចំការលើ', 'chomkar-leu', NULL, NULL),
	(757, 179, 'Kang Cham', 'កាំងចាម', 'kang-cham', NULL, NULL),
	(758, 179, 'Koh Snaeng', 'កោះស្នែង', 'koh-snaeng', NULL, NULL),
	(759, 179, 'Ou Rai', 'អូររៃ', 'ou-rai', NULL, NULL),
	(760, 179, 'Ou Svay', 'អូរស្វាយ', 'ou-svay', NULL, NULL),
	(761, 179, 'Preah Romkel', 'ព្រះរំកិល', 'preah-romkel', NULL, NULL),
	(762, 179, 'Som Ang', 'សំអាង', 'som-ang', NULL, NULL),
	(763, 179, 'Srae Russei', 'ស្រែឫស្សី', 'srae-russei', NULL, NULL),
	(764, 179, 'Thala Borivat', 'ថាឡាបរិវ៉ាត់', 'thala-borivat', NULL, NULL),
	(765, 179, 'Anlong Chrey', 'អន្លង់ជ្រៃ', 'anlong-chrey', NULL, NULL),
	(766, 180, 'Stung Trang', 'ស្ទឹងត្រែង', 'stung-trang', NULL, NULL),
	(767, 180, 'Srah Russei', 'ស្រះឫស្សី', 'srah-russei', NULL, NULL),
	(768, 180, 'Preah Bat', 'ព្រះបាទ', 'preah-bat', NULL, NULL),
	(769, 180, 'Sammaki', 'សាមគ្គី', 'sammaki', NULL, NULL),
	(770, 63, 'Banteay Neang', 'បន្ទាយនាង', 'banteay-neang', NULL, NULL),
	(771, 63, 'Bat Trang', 'បត់ត្រង់', 'bat-trang', NULL, NULL),
	(772, 63, 'Chamnaom', 'ចំណោម', 'chamnaom', NULL, NULL),
	(773, 63, 'Kouk Ballangk', 'គោកបល្ល័ង្គ', 'kouk-ballangk', NULL, NULL),
	(774, 63, 'Koy Maeng', 'គយម៉ែង', 'koy-maeng', NULL, NULL),
	(775, 63, 'Ou Prasat', 'អូរប្រាសាទ', 'ou-prasat', NULL, NULL),
	(776, 63, 'Phnum Touch', 'ភ្នំតូច', 'phnum-touch', NULL, NULL),
	(777, 63, 'Rohat Tuek', 'រហាត់ទឹក', 'rohat-tuek', NULL, NULL),
	(778, 63, 'Ruessei Kraok', 'ឫស្សីក្រោក', 'ruessei-kraok', NULL, NULL),
	(779, 63, 'Sambuor', 'សំបួរ', 'sambuor', NULL, NULL),
	(780, 63, 'Soea', 'សឿ', 'soea', NULL, NULL),
	(781, 63, 'Srah Reang ', 'ស្រះរាំង', 'srah-reang', NULL, NULL),
	(782, 63, 'Ta Lam', 'តាឡំ', 'ta-lam', NULL, NULL),
	(783, 64, 'Chhnuor Mean Chey', 'ឈ្នួរមានជ័យ', 'chhnuor-mean-chey', NULL, NULL),
	(784, 64, 'Chob Veari', 'ជប់វារី', 'chob-veari', NULL, NULL),
	(785, 64, 'Phnum Lieb', 'ភ្នំលៀប', 'phnum-lieb', NULL, NULL),
	(786, 64, 'Prasat', 'ប្រាសាទ', 'prasat', NULL, NULL),
	(787, 64, 'Preah Netr Preah', 'ព្រះនេត្រព្រះ', 'preah-netr-preah', NULL, NULL),
	(788, 64, 'Rohal', 'រហាល', 'rohal', NULL, NULL),
	(789, 64, 'Tean Kam', 'ទានកាំ', 'tean-kam', NULL, NULL),
	(790, 64, 'Tuek Chour', 'ទឹកជោរ', 'tuek-chour', NULL, NULL),
	(791, 65, 'Bos Sbov', 'បុស្បូវ', 'bos-sbov', NULL, NULL),
	(792, 65, 'Kampong Svay', 'កំពង់ស្វាយ', 'kampong-svay', NULL, NULL),
	(793, 65, 'Kaoh Pong Satv', 'កោះពងសត្វ', 'kaoh-pong-satv', NULL, NULL),
	(794, 65, 'Mkak', 'ម្កាក់', 'mkak', NULL, NULL),
	(795, 65, 'Ou Ambel', 'អូរអំបិល', 'ou-ambel', NULL, NULL),
	(796, 65, 'Phniet', 'ភ្នៀត', 'phniet', NULL, NULL),
	(797, 65, 'Preah Ponlea', 'ព្រះពន្លា', 'preah-ponlea', NULL, NULL),
	(798, 65, 'Tuek Thla', 'ទឹកថ្លា', 'tuek-thla', NULL, NULL),
	(799, 66, 'Phkoam', 'ផ្គាំ', 'phkoam', NULL, NULL),
	(800, 66, 'Sarongk', 'សារង្គ', 'sarongk', NULL, NULL),
	(801, 66, 'Sla Kram', 'ស្លក្រាម', 'sla-kram', NULL, NULL),
	(802, 66, 'Svay Chek', 'ស្វាយចេក', 'svay-chek', NULL, NULL),
	(803, 66, 'Ta Baen', 'តាបែន', 'ta-baen', NULL, NULL),
	(804, 66, 'Ta Phou', 'តាផូ', 'ta-phou', NULL, NULL),
	(805, 66, 'Treas', 'ទ្រាស', 'treas', NULL, NULL),
	(806, 66, 'Roluos', 'រលួស', 'roluos', NULL, NULL),
	(807, 67, 'Changha', 'ចង្ហា', 'changha', NULL, NULL),
	(808, 67, 'Koub', 'កូប', 'koub', NULL, NULL),
	(809, 67, 'Kuttasat', 'គុត្តសត', 'kuttasat', NULL, NULL),
	(810, 67, 'Nimitt', 'និមិត្ត', 'nimitt', NULL, NULL),
	(811, 67, 'Samraong', 'សំរោង', 'samraong', NULL, NULL),
	(812, 67, 'Souphi', 'សូភី', 'souphi', NULL, NULL),
	(813, 67, 'Soengh', 'សឹង្ហ', 'soengh', NULL, NULL),
	(814, 67, 'Paoy Paet', 'ប៉ោយប៉ែត', 'paoy-paet', NULL, NULL),
	(815, 67, 'Ou Bei Choan', 'អូរបីជាន់', 'ou-bei-choan', NULL, NULL),
	(816, 68, 'Banteay Chhmar', 'បន្ទាយឆ្មារ', 'banteay-chhmar', NULL, NULL),
	(817, 68, 'Kouk Romiet', 'គោករមៀត', 'kouk-romiet', NULL, NULL),
	(818, 68, 'Phum Thmei', 'ថ្មពួក', 'phum-thmei', NULL, NULL),
	(819, 68, 'Thma Puok', 'គោកកឋិន', 'thma-puok', NULL, NULL),
	(820, 68, 'Kouk Kakthen', 'គំរូ', 'kouk-kakthen', NULL, NULL),
	(821, 68, 'Kumru', 'ភូមិថ្មី', 'kumru', NULL, NULL),
	(822, 69, 'Boeng Beng', 'បឹងបេង', 'boeng-beng', NULL, NULL),
	(823, 69, 'Malai', 'ម៉ាឡៃ', 'malai', NULL, NULL),
	(824, 69, 'Ou Sampor', 'អូរសំព័រ', 'ou-sampor', NULL, NULL),
	(825, 69, 'Ou Sralau', 'អូរស្រឡៅ', 'ou-sralau', NULL, NULL),
	(826, 69, 'Tuol Pongro', 'ទួលពង្រ', 'tuol-pongro', NULL, NULL),
	(827, 69, 'Ta Kong', 'តាគង់', 'ta-kong', NULL, NULL),
	(828, 70, 'Changha', 'ចង្ហា', 'changha', NULL, NULL),
	(829, 70, 'Koub', 'កូប', 'koub', NULL, NULL),
	(830, 70, 'Kuttasat', 'គុត្តសត', 'kuttasat', NULL, NULL),
	(831, 70, 'Nimitt', 'និមិត្ត', 'nimitt', NULL, NULL),
	(832, 70, 'Samraong', 'សំរោង', 'samraong', NULL, NULL),
	(833, 70, 'Souphi', 'សូភី', 'souphi', NULL, NULL),
	(834, 70, 'Soengh', 'សឹង្ហ', 'soengh', NULL, NULL),
	(835, 70, 'Paoy Paet', 'ប៉ោយប៉ែត', 'paoy-paet', NULL, NULL),
	(836, 70, 'Ou Bei Choan', 'អូរបីជាន់', 'ou-bei-choan', NULL, NULL),
	(837, 71, 'Nam Tau', 'ណាំតៅ', 'nam-tau', NULL, NULL),
	(838, 71, 'Paoy Char', 'ប៉ោយចារ', 'paoy-char', NULL, NULL),
	(839, 71, 'Ponley', 'ពន្លៃ', 'ponley', NULL, NULL),
	(840, 71, 'Spean Sraeng', 'ស្ពានស្រែង', 'spean-sraeng', NULL, NULL),
	(841, 71, 'Srah Chik', 'ស្រះជីក', 'srah-chik', NULL, NULL),
	(842, 71, 'Phnum Dei', 'ភ្នំដី', 'phnum-dei', NULL, NULL),
	(843, 72, 'Anhchanh Rung', 'អញ្ចាញរូង', 'anhchanh-rung', NULL, NULL),
	(844, 72, 'Chhnok Tru', 'ឆ្នុកទ្រូ', 'chhnok-tru', NULL, NULL),
	(845, 72, 'Chak', 'ចក', 'chak', NULL, NULL),
	(846, 72, 'Khon Rang', 'ខុនរ៉ង', 'khon-rang', NULL, NULL),
	(847, 72, 'Kampong Preah Kokir', 'កំពង់ព្រះគគីរ', 'kampong-preah-kokir', NULL, NULL),
	(848, 72, 'Melum', 'មេលំ', 'melum', NULL, NULL),
	(849, 72, 'Phsar', 'ផ្សារ', 'phsar', NULL, NULL),
	(850, 72, 'Pech Changvar', 'ពេជ្រចង្វារ', 'pech-changvar', NULL, NULL),
	(851, 72, 'Popel', 'ពពេល', 'popel', NULL, NULL),
	(852, 72, 'Ponley', 'ពន្លៃ', 'ponley', NULL, NULL),
	(853, 72, 'Trapeang Chan', 'ត្រពាំងចាន់', 'trapeang-chan', NULL, NULL),
	(854, 73, 'Phsar Chhnang', 'ផ្សារឆ្នាំង', 'phsar-chhnang', NULL, NULL),
	(855, 73, 'Kampong Chhnang', 'កំពង់ឆ្នាំង', 'kampong-chhnang', NULL, NULL),
	(856, 73, 'Pha er', 'ប្អេរ', 'pha-er', NULL, NULL),
	(857, 73, 'Khsam', 'ខ្សាម', 'khsam', NULL, NULL),
	(858, 74, 'Ampil Tuek', 'អំពិលទឹក', 'ampil-tuek', NULL, NULL),
	(859, 74, 'Chhuk Sa', 'ឈូកស', 'chhuk-sa', NULL, NULL),
	(860, 74, 'Chres', 'ច្រេស', 'chres', NULL, NULL),
	(861, 74, 'Kampong Tralach', 'កំពង់ត្រឡាច', 'kampong-tralach', NULL, NULL),
	(862, 74, 'Longveaek', 'លង្វែក', 'longveaek', NULL, NULL),
	(863, 74, 'Ou Ruessei', 'អូរឬស្សី', 'ou-ruessei', NULL, NULL),
	(864, 74, 'Peani', 'ពានី', 'peani', NULL, NULL),
	(865, 74, 'Saeb', 'សែប', 'saeb', NULL, NULL),
	(866, 74, 'Ta Ches', 'តាជេស', 'ta-ches', NULL, NULL),
	(867, 74, 'Thma Edth', 'ថ្មឥដ្ឋ', 'thma-edth', NULL, NULL),
	(868, 75, 'Chhean Laeung', 'ឈានឡើង', 'chhean-laeung', NULL, NULL),
	(869, 75, 'Khnar Chhmar', 'ខ្នាឆ្មារ', 'khnar-chhmar', NULL, NULL),
	(870, 75, 'Krang Lvea', 'រាំល្វា', 'krang-lvea', NULL, NULL),
	(871, 75, 'Peam', 'ពាម', 'peam', NULL, NULL),
	(872, 75, 'Sedthei', 'សេដ្ឋី', 'sedthei', NULL, NULL),
	(873, 75, 'Svay', 'ស្វាយ', 'svay', NULL, NULL),
	(874, 75, 'Svay Chuk', 'ស្វាយជុក', 'svay-chuk', NULL, NULL),
	(875, 75, 'Tbaeng Khpos', 'ត្បែងខ្ពស់', 'tbaeng-khpos', NULL, NULL),
	(876, 75, 'Thlok Vien', 'ធ្លកវៀន', 'thlok-vien', NULL, NULL),
	(877, 76, 'Chranouk', 'ច្រណូក', 'chranouk', NULL, NULL),
	(878, 76, 'Dar', 'ដារ', 'dar', NULL, NULL),
	(879, 76, 'Kampong hau', 'កំពង់ហៅ', 'kampong-hau', NULL, NULL),
	(880, 76, 'Phlov Tuk', 'ផ្លូវទូក', 'phlov-tuk', NULL, NULL),
	(881, 76, 'Pou', 'ពោធិ៍', 'pou', NULL, NULL),
	(882, 76, 'Pralay Meas', 'ប្រឡាយមាស', 'pralay-meas', NULL, NULL),
	(883, 76, 'Samraong Saen', 'សំរោងសែន', 'samraong-saen', NULL, NULL),
	(884, 76, 'Svay Rumpear', 'ស្វាយរំពារ', 'svay-rumpear', NULL, NULL),
	(885, 76, 'Trangel', 'ត្រងិល', 'trangel', NULL, NULL),
	(886, 77, 'Chol Sarg', 'ជលសា', 'chol-sarg', NULL, NULL),
	(887, 77, 'Kaoh Thkov', 'កោះថ្កូវ', 'kaoh-thkov', NULL, NULL),
	(888, 77, 'Kampong Os', 'កំពង់អុស', 'kampong-os', NULL, NULL),
	(889, 77, 'Peam Chhkaok', 'ពាមឆ្កោក', 'peam-chhkaok', NULL, NULL),
	(890, 77, 'Prey Kri', 'ព្រៃគ្រី', 'prey-kri', NULL, NULL),
	(891, 78, 'Andoung Snay', 'អណ្តូងស្នាយ', 'andoung-snay', NULL, NULL),
	(892, 78, 'Banteay Preal', 'បន្ទាយព្រាល', 'banteay-preal', NULL, NULL),
	(893, 78, 'Cheung Kreav', 'ជើងគ្រាវ', 'cheung-kreav', NULL, NULL),
	(894, 78, 'Chrey Bak', 'ជ្រៃបាក់', 'chrey-bak', NULL, NULL),
	(895, 78, 'Kouk Banteay', 'គោកបន្ទាយ', 'kouk-banteay', NULL, NULL),
	(896, 78, 'Krang Leav', 'ក្រាំងលាវ', 'krang-leav', NULL, NULL),
	(897, 78, 'Pongro', 'ពង្រ', 'pongro', NULL, NULL),
	(898, 78, 'Prasneb', 'ប្រស្នឹប', 'prasneb', NULL, NULL),
	(899, 78, 'Prey Mul', 'ព្រៃមូល', 'prey-mul', NULL, NULL),
	(900, 78, 'Rolea Ba ier', 'រលាប្អៀរ', 'rolea-ba-ier', NULL, NULL),
	(901, 78, 'Srae Thmei', 'ស្រែថ្មី', 'srae-thmei', NULL, NULL),
	(902, 78, 'Svay Chrum', 'ស្វាយជ្រុំ', 'svay-chrum', NULL, NULL),
	(903, 78, 'Tuek Hout', 'ទឹកហូត', 'tuek-hout', NULL, NULL),
	(904, 79, 'Akphivoadth ', 'អភិវឌ្ឍន៍', 'akphivoadth', NULL, NULL),
	(905, 79, 'Chieb ', 'ជៀប', 'chieb', NULL, NULL),
	(906, 79, 'Chaong Maong', 'ចោងម៉ោង', 'chaong-maong', NULL, NULL),
	(907, 79, 'Kbal Tuek', 'ក្បាលទឹក', 'kbal-tuek', NULL, NULL),
	(908, 79, 'Khlong Popok', 'ខ្លុងពពក', 'khlong-popok', NULL, NULL),
	(909, 79, 'Krang Skear', 'រាំងស្គារ', 'krang-skear', NULL, NULL),
	(910, 79, 'Tang Krasang', 'តាំងក្រសាំង', 'tang-krasang', NULL, NULL),
	(911, 79, 'Tuol Khpos', 'ទួលខ្ពស់', 'tuol-khpos', NULL, NULL),
	(912, 130, 'Pailin', NULL, 'pailin', NULL, NULL),
	(913, 130, 'Ou Tavau', NULL, 'ou-tavau', NULL, NULL),
	(914, 130, 'Tuol Lvea', NULL, 'tuol-lvea', NULL, NULL),
	(915, 130, 'Ba Yakha', NULL, 'ba-yakha', NULL, NULL),
	(916, 131, 'Sala Krau', NULL, 'sala-krau', NULL, NULL),
	(917, 131, 'Stueng Trang', NULL, 'stueng-trang', NULL, NULL),
	(918, 131, 'Stueng Kach', NULL, 'stueng-kach', NULL, NULL),
	(919, 131, 'Ou Andoung', NULL, 'ou-andoung', NULL, NULL),
	(920, 125, 'Anlong Veaeng', NULL, 'anlong-veaeng', NULL, NULL),
	(921, 125, 'Trapeang Tav', NULL, 'trapeang-tav', NULL, NULL),
	(922, 125, 'Trapeang Prei', NULL, 'trapeang-prei', NULL, NULL),
	(923, 125, 'Thlat', NULL, 'thlat', NULL, NULL),
	(924, 125, 'Lumtong', NULL, 'lumtong', NULL, NULL),
	(925, 126, 'Ampil', NULL, 'ampil', NULL, NULL),
	(926, 126, 'Beng', NULL, 'beng', NULL, NULL),
	(927, 126, 'Kouk Khpos', NULL, 'kouk-khpos', NULL, NULL),
	(928, 126, 'Kouk Mon', NULL, 'kouk-mon', NULL, NULL),
	(929, 127, 'Cheung Tien', NULL, 'cheung-tien', NULL, NULL),
	(930, 127, 'Chong Kal', NULL, 'chong-kal', NULL, NULL),
	(931, 127, 'Krasang', NULL, 'krasang', NULL, NULL),
	(932, 127, 'Pongro', NULL, 'pongro', NULL, NULL),
	(933, 128, 'Bansay Reak', NULL, 'bansay-reak', NULL, NULL),
	(934, 128, 'Bos Sbov', NULL, 'bos-sbov', NULL, NULL),
	(935, 128, 'Kriel', NULL, 'kriel', NULL, NULL),
	(936, 128, 'Samraong', NULL, 'samraong', NULL, NULL),
	(937, 128, 'Ou Smach', NULL, 'ou-smach', NULL, NULL),
	(938, 129, 'Bak Anlung', NULL, 'bak-anlung', NULL, NULL),
	(939, 129, 'Ph\'av', NULL, 'phav', '2020-07-31 12:17:06', NULL),
	(940, 129, 'Ou Svay', NULL, 'ou-svay', NULL, NULL),
	(941, 129, 'Preah Pralay', NULL, 'preah-pralay', NULL, NULL),
	(942, 129, 'Tumnob Dach', NULL, 'tumnob-dach', NULL, NULL),
	(943, 12, 'Trapeang Prasat', NULL, 'trapeang-prasat', NULL, NULL);
/*!40000 ALTER TABLE `communes` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
