-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.26 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for thepinrealestate_social_login
DROP DATABASE IF EXISTS `thepinrealestate_social_login`;
CREATE DATABASE IF NOT EXISTS `thepinrealestate_social_login` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `thepinrealestate_social_login`;

-- Dumping structure for table thepinrealestate_social_login.districts
DROP TABLE IF EXISTS `districts`;
CREATE TABLE IF NOT EXISTS `districts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `province_id` int(11) DEFAULT NULL,
  `name_en` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_kh` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `slug` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=198 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table thepinrealestate_social_login.districts: 197 rows
/*!40000 ALTER TABLE `districts` DISABLE KEYS */;
INSERT INTO `districts` (`id`, `province_id`, `name_en`, `name_kh`, `slug`, `created_at`, `updated_at`) VALUES
	(1, 1, 'Ruessei Kaev', 'ឫស្សីកែវ', 'ruessei-kaev', NULL, NULL),
	(2, 1, 'Saensokh', 'សែនសុខ', 'saensokh', NULL, NULL),
	(3, 1, 'Por Senchey', 'ពោធិសែនជ័យ', 'por-senchey', NULL, NULL),
	(4, 1, 'Chrouy Changva', 'ជ្រោយចង្វារ', 'chrouy-changva', NULL, NULL),
	(5, 1, 'Preaek Pnov', 'ព្រែកភ្នៅ', 'preaek-pnov', NULL, NULL),
	(6, 1, 'Chbar Ampov', 'ច្បារអំពៅ', 'chbar-ampov', NULL, NULL),
	(7, 1, 'Doun Penh', 'ដូនពេញ', 'doun-penh', NULL, NULL),
	(8, 1, 'Prampir Meakkara', '៧មករា', 'prampir-meakkara', NULL, NULL),
	(9, 1, 'Toul Kouk', 'ទួលគោក', 'toul-kouk', NULL, NULL),
	(10, 1, 'Dangkao', 'ដង្កោ', 'dangkao', NULL, NULL),
	(11, 1, 'Mean Chey', 'មានជ័យ', 'mean-chey', NULL, NULL),
	(12, 1, 'Chamkar Mon', 'ចំការមន', 'chamkar-mon', NULL, NULL),
	(13, 2, 'Krong Preah Sihanouk', 'ព្រះសីហនុ', 'krong-preah-sihanouk', NULL, NULL),
	(14, 2, 'Prey Nob', 'ព្រៃនប់', 'prey-nob', NULL, NULL),
	(15, 2, 'Stueng Hav Chey', 'ស្ទឹងហាវ', 'stueng-hav-chey', NULL, NULL),
	(16, 2, 'Kompong Seila', 'កំពង់សីលា', 'kompong-seila', NULL, NULL),
	(17, 3, 'Krong Kampong Cham', 'កំពង់ចាម', 'krong-kampong-cham', NULL, NULL),
	(18, 3, 'Kampong Siem', 'កំពង់សៀម', 'kampong-siem', NULL, NULL),
	(19, 3, 'KangMeas', 'កងមាស', 'kangmeas', NULL, NULL),
	(20, 3, 'Kaoh Soutin', 'កោះសុទិន', 'kaoh-soutin', NULL, NULL),
	(21, 3, 'Prey Chhor', 'ព្រៃឈរ', 'prey-chhor', NULL, NULL),
	(22, 3, 'Srei Santhor', 'ស្រីសន្ធរ', 'srei-santhor', NULL, NULL),
	(23, 3, 'Stueng Trang', 'ស្ទឹងត្រង់', 'stueng-trang', NULL, NULL),
	(24, 3, 'Batheay', 'បាធាយ', 'batheay', NULL, NULL),
	(25, 3, 'Chamkar Leu', 'ចំការលើ', 'chamkar-leu', NULL, NULL),
	(26, 3, 'Cheung Prey', 'ជើងព្រៃ', 'cheung-prey', NULL, NULL),
	(27, 4, 'Angkor Chum', 'អង្គរជុំ', 'angkor-chum', NULL, NULL),
	(28, 4, 'Angkor Thom', 'អង្គរធំ', 'angkor-thom', NULL, NULL),
	(29, 4, 'Banteay Srey', 'បន្ទាយស្រី', 'banteay-srey', NULL, NULL),
	(30, 4, 'Chi Kraeng', 'ជីក្រែង', 'chi-kraeng', NULL, NULL),
	(31, 4, 'Kralanh', 'ក្រឡាញ់', 'kralanh', NULL, NULL),
	(32, 4, 'Pouk', 'ពួក', 'pouk', NULL, NULL),
	(33, 4, 'Prasat Bakong', 'ប្រាសាទបាគង', 'prasat-bakong', NULL, NULL),
	(34, 4, 'Krong Siem Reap', 'ក្រុងសៀមរាប', 'krong-siem-reap', NULL, NULL),
	(35, 4, 'Soutr Nikum', 'សុទ្រនិគមន៍', 'soutr-nikum', NULL, NULL),
	(36, 4, 'Srei Snam', 'ស្រីស្នំ', 'srei-snam', NULL, NULL),
	(37, 4, 'Svay Leu', 'ស្វាយលើ', 'svay-leu', NULL, NULL),
	(38, 4, 'Varin', 'វ៉ារិន', 'varin', NULL, NULL),
	(39, 5, 'Banan', 'បាណន់', 'banan', NULL, NULL),
	(40, 5, 'Thma Koul', 'ថ្មរគោល', 'thma-koul', NULL, NULL),
	(41, 5, 'Krong Battambang', 'ក្រុងបាត់ដំបង', 'krong-battambang', NULL, NULL),
	(42, 5, 'Bavel', 'បវេល', 'bavel', NULL, NULL),
	(43, 5, 'Aek Phnum', 'ឯកភ្នំ', 'aek-phnum', NULL, NULL),
	(44, 5, 'Moung Ruessei', 'មោង រស្សី', 'moung-ruessei', NULL, NULL),
	(45, 5, 'Rotonak Mondol', 'រតនាមណ្ឌល', 'rotonak-mondol', NULL, NULL),
	(46, 5, 'Sangkae', 'សង្កៃរ', 'sangkae', NULL, NULL),
	(47, 5, 'Samlout', 'សំឡូត', 'samlout', NULL, NULL),
	(48, 5, 'Sampov Lun', 'សំពៅលូន', 'sampov-lun', NULL, NULL),
	(49, 5, 'Phnom Proek', 'ភ្នំព្រឹក', 'phnom-proek', NULL, NULL),
	(50, 5, 'Kamrieng', 'កំរៀង', 'kamrieng', NULL, NULL),
	(51, 5, 'Koas Krala', 'គាស់ក្រឡ', 'koas-krala', NULL, NULL),
	(52, 5, 'Rukhak Kiri', 'រុក្ខគីរី', 'rukhak-kiri', NULL, NULL),
	(53, 6, 'Kandal Stueng', '', 'kandal-stueng', NULL, NULL),
	(54, 6, 'Koh Thum', '', 'koh-thum', NULL, NULL),
	(55, 6, 'Mukh Kamphool', '', 'mukh-kamphool', NULL, NULL),
	(56, 6, 'Sa Ang', '', 'sa-ang', NULL, NULL),
	(57, 6, 'Leuk Daek', '', 'leuk-daek', NULL, NULL),
	(58, 6, 'Krong Ta Khmau', '', 'krong-ta-khmau', NULL, NULL),
	(59, 6, 'Kien Svay', '', 'kien-svay', NULL, NULL),
	(60, 6, 'Ponhea Leu', '', 'ponhea-leu', NULL, NULL),
	(61, 6, 'Lvea Aem', '', 'lvea-aem', NULL, NULL),
	(62, 6, 'Khsach Kandal', '', 'khsach-kandal', NULL, NULL),
	(63, 7, 'Mongkol Borei', '', 'mongkol-borei', NULL, NULL),
	(64, 7, 'Preah Netr Preah', '', 'preah-netr-preah', NULL, NULL),
	(65, 7, 'Serei Saophoan', '', 'serei-saophoan', NULL, NULL),
	(66, 7, 'Svay Chek', '', 'svay-chek', NULL, NULL),
	(67, 7, 'Ou Chrov', '', 'ou-chrov', NULL, NULL),
	(68, 7, 'Thma Puok', '', 'thma-puok', NULL, NULL),
	(69, 7, 'Malai', '', 'malai', NULL, NULL),
	(70, 7, 'Ou Chrov', '', 'ou-chrov', NULL, NULL),
	(71, 7, 'Phnum Srok', '', 'phnum-srok', NULL, NULL),
	(72, 8, 'Baribour', '', 'baribour', NULL, NULL),
	(73, 8, 'Kampong Chhnang', '', 'kampong-chhnang', NULL, NULL),
	(74, 8, 'Kampong Tralach', '', 'kampong-tralach', NULL, NULL),
	(75, 8, 'Sameakki', '', 'sameakki', NULL, NULL),
	(76, 8, 'Kampong Leaeng', '', 'kampong-leaeng', NULL, NULL),
	(77, 8, 'Chol Kiri', '', 'chol-kiri', NULL, NULL),
	(78, 8, 'Rolea B\'ier', '', 'rolea-bier', NULL, NULL),
	(79, 8, 'Tuek Phos', '', 'tuek-phos', NULL, NULL),
	(80, 9, 'Basedth', '', 'basedth', NULL, NULL),
	(81, 9, 'Kong Pisei', '', 'kong-pisei', NULL, NULL),
	(82, 9, 'Odongk', '', 'odongk', NULL, NULL),
	(83, 9, 'Samraong Tong', '', 'samraong-tong', NULL, NULL),
	(84, 9, 'Aoral', '', 'aoral', NULL, NULL),
	(85, 9, 'Phnom Sruoch', '', 'phnom-sruoch', NULL, NULL),
	(86, 9, 'Chbar Mon', '', 'chbar-mon', NULL, NULL),
	(87, 9, 'Thpong', '', 'thpong', NULL, NULL),
	(88, 10, 'Baray', '', 'baray', NULL, NULL),
	(89, 10, 'Stueng Saen', '', 'stueng-saen', NULL, NULL),
	(90, 10, 'Sandaan', '', 'sandaan', NULL, NULL),
	(91, 10, 'Stoung', '', 'stoung', NULL, NULL),
	(92, 10, 'Prasat Balangk', '', 'prasat-balangk', NULL, NULL),
	(93, 10, 'Santuk', '', 'santuk', NULL, NULL),
	(94, 10, 'Prasat Sambour', '', 'prasat-sambour', NULL, NULL),
	(95, 10, 'Kampong Svay', '', 'kampong-svay', NULL, NULL),
	(96, 11, 'Angkor Chey', '', 'angkor-chey', NULL, NULL),
	(97, 11, 'Chhuk', '', 'chhuk', NULL, NULL),
	(98, 11, 'Dorng Tong', '', 'dorng-tong', NULL, NULL),
	(99, 11, 'Teouk Chhou', '', 'teouk-chhou', NULL, NULL),
	(100, 11, 'Banteay Meas', '', 'banteay-meas', NULL, NULL),
	(101, 11, 'Kampong Trach', '', 'kampong-trach', NULL, NULL),
	(102, 11, 'Chum Kiri', '', 'chum-kiri', NULL, NULL),
	(103, 11, 'Kampot', '', 'kampot', NULL, NULL),
	(104, 12, 'Krong Kep', '', 'krong-kep', NULL, NULL),
	(105, 12, 'Damnak Chang aeur', '', 'damnak-chang-aeur', NULL, NULL),
	(106, 12, 'Krong Kep', '', 'krong-kep', NULL, NULL),
	(107, 13, 'Botum Sakor', '', 'botum-sakor', NULL, NULL),
	(108, 13, 'Koh Kong', '', 'koh-kong', NULL, NULL),
	(109, 13, 'Mondol Seima', '', 'mondol-seima', NULL, NULL),
	(110, 13, 'Thma Bang', '', 'thma-bang', NULL, NULL),
	(111, 13, 'Kiri Sakor', '', 'kiri-sakor', NULL, NULL),
	(112, 13, 'Khemara Phoumin', '', 'khemara-phoumin', NULL, NULL),
	(113, 13, 'Srae Ambel', '', 'srae-ambel', NULL, NULL),
	(114, 14, 'Chhlong', '', 'chhlong', NULL, NULL),
	(115, 14, 'Chitr Borei', '', 'chitr-borei', NULL, NULL),
	(116, 14, 'Krong Kratie', '', 'krong-kratie', NULL, NULL),
	(117, 14, 'Sombo', '', 'sombo', NULL, NULL),
	(118, 14, 'Preaek Prasob', '', 'preaek-prasob', NULL, NULL),
	(119, 14, 'Snoul', '', 'snoul', NULL, NULL),
	(120, 15, 'Kaev Seima', '', 'kaev-seima', NULL, NULL),
	(121, 15, 'Ou Reang', '', 'ou-reang', NULL, NULL),
	(122, 15, 'Krong Saen', '', 'krong-saen', NULL, NULL),
	(123, 15, 'Pech Chreada', '', 'pech-chreada', NULL, NULL),
	(124, 15, 'Kaoh Nheaek', '', 'kaoh-nheaek', NULL, NULL),
	(125, 16, 'Anlong Veaeng', '', 'anlong-veaeng', NULL, NULL),
	(126, 16, 'Banteay Ampil', '', 'banteay-ampil', NULL, NULL),
	(127, 16, 'Chong Kal', '', 'chong-kal', NULL, NULL),
	(128, 16, 'Krong Samraong', '', 'krong-samraong', NULL, NULL),
	(129, 16, 'Trapeang Prasat', '', 'trapeang-prasat', NULL, NULL),
	(130, 17, 'Krong Pailin', '', 'krong-pailin', NULL, NULL),
	(131, 17, 'Sala Krau', '', 'sala-krau', NULL, NULL),
	(132, 17, 'Chong Kal', '', 'chang-kal', NULL, NULL),
	(133, 18, 'Chey Saen', '', 'chey-saen', NULL, NULL),
	(134, 18, 'Choam Khsant', '', 'choam-khsant', NULL, NULL),
	(135, 18, 'Rovieng', '', 'rovieng', NULL, NULL),
	(136, 18, 'Sangkom Thmei', '', 'sangkom-thmei', NULL, NULL),
	(137, 18, 'Chhaeb', '', 'chhaeb', NULL, NULL),
	(138, 18, 'Kulen', '', 'kulen', NULL, NULL),
	(139, 18, 'Tbaeng Mean Chey', '', 'tbaeng-mean-chey', NULL, NULL),
	(140, 18, 'Krong Preah Vihear', '', 'krong-preah-vihear', NULL, NULL),
	(141, 19, 'Ba Phnum', '', 'ba-phnum', NULL, NULL),
	(142, 19, 'Kanhchriech', '', 'kanhchriech', NULL, NULL),
	(143, 19, 'Peam Ro', '', 'peam-ro', NULL, NULL),
	(144, 19, 'Preah Sdach', '', 'preah-sdach', NULL, NULL),
	(145, 19, 'Me Sang', '', 'me-sang', NULL, NULL),
	(146, 19, 'Pea Reang', '', 'pea-reang', NULL, NULL),
	(147, 19, 'Kamchay Mear', '', 'kamchay-mear', NULL, NULL),
	(148, 19, 'Prey Veaeng', '', 'prey-veaeng', NULL, NULL),
	(149, 19, 'Peam Chor', '', 'peam-chor', NULL, NULL),
	(150, 19, 'Kampong Trabaek', '', 'kampong-trabaek', NULL, NULL),
	(151, 19, 'Por Reang', '', 'por-reang', NULL, NULL),
	(152, 19, 'Svay Ontor', '', 'svay-ontor', NULL, NULL),
	(153, 20, 'Bakan', '', 'bakan', NULL, NULL),
	(154, 20, 'Krakor', '', 'krakor', NULL, NULL),
	(155, 20, 'Krong Pursat', '', 'krong-pursat', NULL, NULL),
	(156, 20, 'Kandieng', '', 'kandieng', NULL, NULL),
	(157, 20, 'Phnum Kravanh', '', 'phnum-kravanh', NULL, NULL),
	(158, 20, 'Veal Veaeng', '', 'veal-veaeng', NULL, NULL),
	(159, 21, 'Andoung Meas', '', 'andoung-meas', NULL, NULL),
	(160, 21, 'Koun Mom', '', 'koun-mom', NULL, NULL),
	(161, 21, 'Ou Chum', '', 'ou-chum', NULL, NULL),
	(162, 21, 'Ta Veaeng', '', 'ta-veaeng', NULL, NULL),
	(163, 21, 'Krong Banlung', '', 'krong-banlung', NULL, NULL),
	(164, 21, 'Lumphat', '', 'lumphat', NULL, NULL),
	(165, 21, 'Ou Ya Dav', '', 'ou-ya-dav', NULL, NULL),
	(166, 21, 'Bar Kaev', '', 'bar-kaev', NULL, NULL),
	(167, 22, 'Sesan', '', 'sesan', NULL, NULL),
	(168, 22, 'Siem Bouk', '', 'siem-bouk', NULL, NULL),
	(169, 22, 'Siem Pang', '', 'siem-pang', NULL, NULL),
	(170, 22, 'Thala Barivat', '', 'thala-barivat', NULL, NULL),
	(171, 22, 'Krong Stung Treng', '', 'krong-stung-treng', NULL, NULL),
	(172, 23, 'Chantrea', '', 'chantrea', NULL, NULL),
	(173, 23, 'Rumduol', '', 'rumduol', NULL, NULL),
	(174, 23, 'Svay Chrum', '', 'svay-chrum', NULL, NULL),
	(175, 23, 'Svay Teab', '', 'svay-teab', NULL, NULL),
	(176, 23, 'Kampong Rou', '', 'kampong-rou', NULL, NULL),
	(177, 23, 'Romeas Haek', '', 'romeas-haek', NULL, NULL),
	(178, 23, 'Krong Bavet', '', 'krong-bavet', NULL, NULL),
	(179, 23, 'Krong Svay Rieng', '', 'krong-svay-rieng', NULL, NULL),
	(180, 24, 'Angkor Borei', '', 'angkor-borei', NULL, NULL),
	(181, 24, 'Kiri Vong', '', 'kiri-vong', NULL, NULL),
	(182, 24, 'Samraong', '', 'samraong', NULL, NULL),
	(183, 24, 'Treang', '', 'treang', NULL, NULL),
	(184, 24, 'Bati', '', 'bati', NULL, NULL),
	(185, 24, 'Krong Doun Kaev', '', 'krong-doun-kaev', NULL, NULL),
	(186, 24, 'Kaoh Andaet', '', 'kaoh-andaet', NULL, NULL),
	(187, 24, 'Krong Doun Kaev', '', 'krong-doun-kaev', NULL, NULL),
	(188, 24, 'Tram Kak', '', 'tram-kak', NULL, NULL),
	(189, 24, 'Prey Kabbas', '', 'prey-kabbas', NULL, NULL),
	(190, 24, 'Bourei Cholsar', '', 'bourei-cholsar', NULL, NULL),
	(191, 25, 'Dombae', '', 'dombae', NULL, NULL),
	(192, 25, 'Memot', '', 'memot', NULL, NULL),
	(193, 25, 'Ponhea Kraek', '', 'ponhea-kraek', NULL, NULL),
	(194, 25, 'Krouch Chhma', '', 'krouch-chhma', NULL, NULL),
	(195, 25, 'Tboung Khmum', '', 'tboung-khmum', NULL, NULL),
	(196, 25, 'Ou Reang Ov', '', 'ou-reang-ov', NULL, NULL),
	(197, 25, 'Krong Suong', '', 'krong-suong', NULL, NULL);
/*!40000 ALTER TABLE `districts` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
